/**
/**
 * OFFICIAL HASHTAG DICTIONARY & ANNOTATIONS FOR TRADING METHODOLOGY
 * Centralized registry for all trading setups, trends, session tags, mistakes, and discipline habits.
 */

export const OFFICIAL_HASHTAGS = {
  sessions: [
    {
      tag: '#Session_Asia',
      label: 'Phiên Á (06:00 - 13:00)',
      zh_label: '亚洲时段（06:00 - 13:00）',
      ko_label: '아시아 세션 (06:00 - 13:00)',
      es_label: 'Sesión asiática (06:00 - 13:00)',
      en_label: 'Asian Session (06:00 - 13:00)',
      category: 'sessions',
      group: 'Khung Thời Gian',
      zh_group: '时间框架 / 交易时段',
      ko_group: '타임프레임 / 세션',
      es_group: 'Marco de Tiempo / Sesión',
      en_group: 'Timeframe / Session',
      description: 'Phiên giao dịch châu Á: Thanh khoản thấp, biên độ hẹp (10-30 pips với Vàng/Forex). Giá chủ yếu Sideway tích lũy tạo nền biên trên/biên dưới.',
      zh_description: '亚洲交易时段：流动性低，波动范围窄（黄金/外汇 10-30 点）。价格主要通过横盘整理来形成上/下边界底部。',
      ko_description: '아시아 거래 세션: 낮은 유동성, 좁은 범위(금/외환의 경우 10-30핍). 가격은 주로 Sideways로 축적되어 상하 경계선 기반을 만듭니다.',
      es_description: 'Sesión comercial asiática: Baja liquidez, rango estrecho (10-30 pips para oro/Forex). El precio se acumula principalmente lateralmente para crear una base de borde superior/inferior.',
      en_description: 'Asian trading session: Low liquidity, narrow range (10-30 pips for Gold/Forex). Price mainly accumulates Sideways to create an upper/lower border base.',
      rules: 'Hạn chế đánh Breakout đuổi. Ưu tiên đánh đảo chiều tại 2 biên tích lũy hoặc chờ Phiên Âu xác nhận xu hướng.',
      zh_rules: '限制突破追逐。优先在2个吸筹边界反转或等待欧洲时段确认趋势。',
      ko_rules: '한계 돌파 추격. 2개의 축적 경계에서 반전을 우선시하거나 유럽 세션에서 추세를 확인할 때까지 기다립니다.',
      es_rules: 'Limita la persecución de fugas. Priorizar la reversión en 2 fronteras de acumulación o esperar a que la sesión europea confirme la tendencia.',
      en_rules: 'Limit Breakout chasing. Prioritize reversal at 2 accumulation borders or wait for the European session to confirm the trend.',
      riskLevel: 'Thấp',
      zh_riskLevel: '低',
      ko_riskLevel: '낮음',
      es_riskLevel: 'Bajo',
      en_riskLevel: 'Low',
      color: 'text-amber-400 border-amber-500/30 bg-amber-500/10'
    },
    {
      tag: '#Session_London',
      label: 'Phiên Âu (14:00 - 19:00)',
      zh_label: '欧洲时段（14:00 - 19:00）',
      ko_label: '유럽 ​​세션 (14:00 - 19:00)',
      es_label: 'Sesión Europea (14:00 - 19:00)',
      en_label: 'European Session (14:00 - 19:00)',
      category: 'sessions',
      group: 'Khung Thời Gian',
      zh_group: '时间框架 / 交易时段',
      ko_group: '타임프레임 / 세션',
      es_group: 'Marco de Tiempo / Sesión',
      en_group: 'Timeframe / Session',
      description: 'Phiên giao dịch châu Âu: Thanh khoản bùng nổ mạnh mẽ, thường xuất hiện cú Quét Thanh Khoản (Fakeout/Sweep) đỉnh/đáy Phiên Á trước khi hình thành xu hướng chính.',
      zh_description: '欧洲交易时段：流动性强劲爆发，亚洲时段顶部/底部经常出现假突破/横扫，然后形成主要趋势。',
      ko_description: '유럽 ​​거래 세션: 유동성이 크게 폭발하며 주요 추세를 형성하기 전에 아시아 세션의 상단/하단에서 페이크아웃/스윕이 발생하는 경우가 많습니다.',
      es_description: 'Sesión de negociación europea: la liquidez explota con fuerza, a menudo hay una falsificación/barrido en la parte superior/inferior de la sesión asiática antes de formar la tendencia principal.',
      en_description: 'European trading session: Liquidity explodes strongly, there is often a Fakeout/Sweep at the top/bottom of the Asian Session before forming the main trend.',
      rules: 'Canh các nhịp Quét Thanh Khoản đỉnh/đáy phiên Á đầu phiên Âu (14:30 - 15:30) để vào lệnh thuận sóng.',
      zh_rules: '观察亚洲时段顶部/底部和欧洲时段开始时（14:30 - 15:30）的流动性扫描节奏，以便跟随波浪输入订单。',
      ko_rules: '웨이브에 따라 주문을 입력하려면 아시아 세션의 상단/하단과 유럽 세션 시작(14:30 - 15:30)의 유동성 스캔 리듬을 시청하세요.',
      es_rules: 'Observe los ritmos del Liquidity Scan en la parte superior/inferior de la sesión asiática y al comienzo de la sesión europea (14:30 - 15:30) para ingresar órdenes siguiendo la ola.',
      en_rules: 'Watch the Liquidity Scan rhythms at the top/bottom of the Asian session and the beginning of the European session (14:30 - 15:30) to enter orders following the wave.',
      riskLevel: 'Trung Bình',
      zh_riskLevel: '中',
      ko_riskLevel: '보통',
      es_riskLevel: 'Medio',
      en_riskLevel: 'Medium',
      color: 'text-sky-400 border-sky-500/30 bg-sky-500/10'
    },
    {
      tag: '#Session_NY',
      label: 'Phiên Mỹ (19:30 - 03:00)',
      zh_label: '美国时段 (19:30 - 03:00)',
      ko_label: '미국 세션 (19:30 - 03:00)',
      es_label: 'Sesión Americana (19:30 - 03:00)',
      en_label: 'American Session (19:30 - 03:00)',
      category: 'sessions',
      group: 'Khung Thời Gian',
      zh_group: '时间框架 / 交易时段',
      ko_group: '타임프레임 / 세션',
      es_group: 'Marco de Tiempo / Sesión',
      en_group: 'Timeframe / Session',
      description: 'Phiên Mỹ: Thanh khoản cực lớn, biến động mạnh nhất trong ngày, đặc biệt vào thời điểm ra tin tức kinh tế quan trọng (CPI, NFP, FOMC, PMI).',
      zh_description: '美国时段：流动性巨大，日内波动最强，特别是在重要经济消息（CPI、NFP、FOMC、PMI）发布时。',
      ko_description: '미국 세션: 특히 중요한 경제 뉴스(CPI, NFP, FOMC, PMI)가 발표되는 시점에는 엄청난 유동성과 가장 큰 변동이 있습니다.',
      es_description: 'Sesión estadounidense: enorme liquidez, fluctuaciones más fuertes durante el día, especialmente en el momento de noticias económicas importantes (IPC, NFP, FOMC, PMI).',
      en_description: 'US session: Huge liquidity, strongest fluctuations during the day, especially at the time of important economic news (CPI, NFP, FOMC, PMI).',
      rules: 'Trước giờ tin tức 15 phút không nhồi lệnh mới. Đợi tin ra xong 15-30 phút để thị trường ổn định cấu trúc mới giao dịch.',
      zh_rules: '请勿在新闻时间前 15 分钟插入新订单。等待消息出来15-30分钟，让市场稳定结构后再进行交易。',
      ko_rules: '뉴스 시간 15분 전에는 새로운 주문을 삽입하지 마세요. 거래에 앞서 시장 구조가 안정화될 때까지 15~30분 동안 뉴스가 나올 때까지 기다리십시오.',
      es_rules: 'No inserte nuevos pedidos 15 minutos antes de la hora de noticias. Espere a que salga la noticia durante 15 a 30 minutos para que el mercado estabilice su estructura antes de operar.',
      en_rules: 'Do not insert new orders 15 minutes before news time. Wait for the news to come out for 15-30 minutes for the market to stabilize its structure before trading.',
      riskLevel: 'Cao',
      zh_riskLevel: '高',
      ko_riskLevel: '높음',
      es_riskLevel: 'Alto',
      en_riskLevel: 'High',
      color: 'text-purple-400 border-purple-500/30 bg-purple-500/10'
    },
  ],

  setups: [
    {
      tag: '#Setup_LHRetest',
      label: 'Lower High Retest',
      zh_label: '降低高重测',
      ko_label: '낮음 높음 재시험',
      es_label: 'Repetición de prueba inferior alta',
      en_label: 'Lower High Retest',
      category: 'setups',
      group: 'Thuận Wave (Trend Following)',
      zh_group: '顺势交易 (Trend Following)',
      ko_group: '추세 추종 (Trend Following)',
      es_group: 'Seguimiento de Tendencia',
      en_group: 'Trend Following',
      description: 'Retest đỉnh thấp hơn trong cấu trúc xu hướng Giảm (Lower High). Giá phá cản, hồi nhẹ lên retest vùng kháng cự/đường EMA rồi bị từ chối tiếp tục giảm.',
      zh_description: '重新测试下降趋势结构中的较低高点（较低高点）。价格突破关口，小幅反弹，重新测试阻力区/EMA线，然后遭到拒绝，继续下跌。',
      ko_description: '하락 추세 구조에서 더 낮은 고점을 다시 테스트합니다(낮은 고점). 가격은 장벽을 무너뜨리고 약간 반등하여 저항/EMA 선을 다시 테스트한 후 거부되어 계속 하락했습니다.',
      es_description: 'Nueva prueba del máximo inferior en la estructura de tendencia bajista (Lower High). El precio rompió la barrera, rebotó ligeramente para volver a probar el área de resistencia/línea EMA y luego fue rechazado y continuó cayendo.',
      en_description: 'Retest of the lower high in the Downtrend structure (Lower High). The price broke the barrier, rebounded slightly to retest the resistance/EMA line and then was rejected and continued to decline.',
      rules: '1. H1 & M15 phải là xu hướng Giảm. 2. Đợi nến M5 đóng cửa từ chối (Pinbar/Engulfing giảm) tại điểm retest. 3. SL trên đỉnh LH + 5-10 pips.',
      zh_rules: '1. H1 & M15 必定是下跌趋势。 2. 等待 M5 蜡烛在重新测试点以拒绝（Pinbar/吞没看跌）收盘。 3. SL 高于 LH 顶部 + 5-10 点。',
      ko_rules: '1. H1 및 M15는 하락 추세여야 합니다. 2. M5 캔들이 재테스트 지점에서 거부(Pinbar/Engulfing Bearish)로 마감될 때까지 기다립니다. 3. LH 상단 + 5-10핍보다 높은 SL.',
      es_rules: '1. H1 y M15 deben tener tendencia bajista. 2. Espere a que la vela M5 se cierre en rechazo (Pinbar/engulfing bajista) en el punto de nueva prueba. 3. SL por encima del tope LH + 5-10 pips.',
      en_rules: '1. H1 & M15 must be Downtrend. 2. Wait for the M5 candle to close in rejection (Pinbar/Engulfing bearish) at the retest point. 3. SL above LH top + 5-10 pips.',
      riskLevel: 'Thấp',
      zh_riskLevel: '低',
      ko_riskLevel: '낮음',
      es_riskLevel: 'Bajo',
      en_riskLevel: 'Low',
      color: 'text-emerald-400 border-emerald-500/30 bg-emerald-500/10'
    },
    {
      tag: '#Setup_HLRetest',
      label: 'Higher Low Retest',
      zh_label: '较高低重新测试',
      ko_label: '높음 낮음 재시험',
      es_label: 'Repetición de prueba más alta y más baja',
      en_label: 'Higher Low Retest',
      category: 'setups',
      group: 'Thuận Wave (Trend Following)',
      zh_group: '顺势交易 (Trend Following)',
      ko_group: '추세 추종 (Trend Following)',
      es_group: 'Seguimiento de Tendencia',
      en_group: 'Trend Following',
      description: 'Retest đáy cao hơn trong cấu trúc xu hướng Tăng (Higher Low). Giá phá đỉnh cũ, quay lại retest điểm hỗ trợ vừa vượt qua trước khi tiếp diễn sóng tăng.',
      zh_description: '重新测试上升趋势结构中的较高低点（较高低点）。价格突破旧高，重新测试刚刚经过的支撑点，然后继续上涨。',
      ko_description: '상승 추세 구조의 더 높은 저점을 다시 테스트합니다(더 높은 저점). 가격은 이전 최고점을 돌파하고 상승파가 계속되기 전에 방금 통과한 지지점을 다시 테스트하기 위해 돌아왔습니다.',
      es_description: 'Nueva prueba del mínimo más alto en la estructura de tendencia alcista (Higher Low). El precio rompió el antiguo pico y volvió a probar el punto de soporte que acababa de pasar antes de continuar la onda ascendente.',
      en_description: 'Retest of the higher low in the Uptrend structure (Higher Low). The price broke the old peak and returned to retest the support point just passed before continuing the upward wave.',
      rules: '1. Khung H1 & M15 là xu hướng Tăng. 2. Đợi nến rút chân M5/M1 tại vùng hỗ trợ. 3. Cài SL ngay dưới đáy HL gần nhất.',
      zh_rules: '1. H1 & M15 框架呈上升趋势。 2. 等待蜡烛在支撑区域撤回其腿 M5/M1。 3. 将 SL 安装在最近的 HL 底部的正下方。',
      ko_rules: '1. H1 및 M15 프레임은 상승 추세입니다. 2. 양초가 지지대에서 다리 M5/M1을 빼낼 때까지 기다립니다. 3. 가장 가까운 HL 하단 바로 아래에 SL을 설치합니다.',
      es_rules: '1. Los marcos H1 y M15 son de tendencia alcista. 2. Espere a que la vela retire sus patas M5/M1 en la zona de soporte. 3. Instale SL justo debajo de la parte inferior del HL más cercano.',
      en_rules: '1. H1 & M15 frames are Uptrend. 2. Wait for the candle to withdraw its legs M5/M1 at the support zone. 3. Install SL right below the bottom of the nearest HL.',
      riskLevel: 'Thấp',
      zh_riskLevel: '低',
      ko_riskLevel: '낮음',
      es_riskLevel: 'Bajo',
      en_riskLevel: 'Low',
      color: 'text-emerald-400 border-emerald-500/30 bg-emerald-500/10'
    },
    {
      tag: '#Setup_BreakoutRetest',
      label: 'Phá Vỡ & Retest Vùng Cản',
      zh_label: '断裂和重新测试阻力区',
      ko_label: '중단 및 재테스트 저항 영역',
      es_label: 'Romper y volver a probar la zona de resistencia',
      en_label: 'Break & Retest Resistance Zone',
      category: 'setups',
      group: 'Thuận Wave (Trend Following)',
      zh_group: '顺势交易 (Trend Following)',
      ko_group: '추세 추종 (Trend Following)',
      es_group: 'Seguimiento de Tendencia',
      en_group: 'Trend Following',
      description: 'Giá nén chặt tích lũy sau đó bùng nổ phá vỡ (Breakout) vùng cản cứng (Keylevel/Kháng cự/Hỗ trợ), sau đó quay lại Retest nhẹ nhàng điểm phá vỡ.',
      zh_description: '价格压缩并积累，然后爆炸性突破（突破）硬阻力区域（​​关键位/阻力/支撑），然后返回温和地重新测试突破点。',
      ko_description: '가격은 압축되고 축적된 후 폭발하여 견고한 저항 영역(키레벨/저항/지지)을 돌파(돌파)한 다음 다시 돌아와 한계점을 부드럽게 다시 테스트합니다.',
      es_description: 'El precio se compactó y acumuló, luego explotó para romper (Breakout) la zona de resistencia dura (Nivel clave/Resistencia/Soporte), luego regresó para volver a probar suavemente el punto de ruptura.',
      en_description: 'The price compacted and accumulated then exploded to break (Breakout) the hard resistance zone (Keylevel/Resistance/Support), then returned to gently retest the breaking point.',
      rules: 'Tuyệt đối không nhảy vào mua đuổi nến Breakout mạnh. Kiên nhẫn chờ cây nến hồi (Retest) quay lại vùng bệ đỡ để Entry an toàn với R:R tối ưu.',
      zh_rules: '绝对不要为了追逐强劲的突破蜡烛而买入。耐心等待重新测试蜡烛返回底部，以实现具有最佳 R:R 的安全进入。',
      ko_rules: '절대 강한 브레이크아웃 캔들을 쫓기 위해 뛰어들거나 구매하지 마세요. 최적의 R:R로 안전한 입장을 위해 재테스트 캔들이 베이스로 돌아올 때까지 인내심을 갖고 기다리십시오.',
      es_rules: 'Absolutamente no se lance a comprar para perseguir velas de ruptura fuertes. Espere pacientemente a que la vela Retest regrese a la base para una entrada segura con R:R óptimo.',
      en_rules: 'Absolutely do not jump in and buy to chase strong Breakout candles. Patiently wait for the Retest candle to return to the base for a safe Entry with optimal R:R.',
      riskLevel: 'Trung Bình',
      zh_riskLevel: '中',
      ko_riskLevel: '보통',
      es_riskLevel: 'Medio',
      en_riskLevel: 'Medium',
      color: 'text-emerald-400 border-emerald-500/30 bg-emerald-500/10'
    },
    {
      tag: '#Setup_EMABounce',
      label: 'Bật Nền Đường EMA 20/50',
      zh_label: '打开 20/50 EMA 基础',
      ko_label: '20/50 EMA 베이스 켜기',
      es_label: 'Encienda la base EMA 20/50',
      en_label: 'Turn on the 20/50 EMA Base',
      category: 'setups',
      group: 'Thuận Wave (Trend Following)',
      zh_group: '顺势交易 (Trend Following)',
      ko_group: '추세 추종 (Trend Following)',
      es_group: 'Seguimiento de Tendencia',
      en_group: 'Trend Following',
      description: 'Bắt phản ứng nến bật hồi ngay tại dải đường trung bình động động (Dynamic Support/Resistance EMA 20 hoặc EMA 50) trong xu hướng đang chạy mượt.',
      zh_description: '在平稳运行趋势中，在移动平均线范围（动态支撑/阻力 EMA 20 或 EMA 50）捕捉反弹蜡烛反应。',
      ko_description: '원활하게 진행되는 추세에서 이동 평균 범위(동적 지지/저항 EMA 20 또는 EMA 50)에서 바로 반등 캔들 반응을 포착하세요.',
      es_description: 'Capte la reacción de la vela de rebote justo en el rango de promedio móvil (Soporte/Resistencia Dinámico EMA 20 o EMA 50) en una tendencia que se desarrolla sin problemas.',
      en_description: 'Catch the rebound candle reaction right at the moving average range (Dynamic Support/Resistance EMA 20 or EMA 50) in a smooth running trend.',
      rules: 'Chỉ dùng khi EMA 20/50 đang dốc rõ ràng. Nếu EMA nằm ngang (Sideway) thì không sử dụng setup này.',
      zh_rules: '仅当 EMA 20/50 明显倾斜时使用。如果 EMA 是水平的（横向），请勿使用此设置。',
      ko_rules: 'EMA 20/50이 확실히 경사진 경우에만 사용하십시오. EMA가 수평(측면)인 경우 이 설정을 사용하지 마십시오.',
      es_rules: 'Úselo únicamente cuando EMA 20/50 esté claramente inclinado. Si la EMA es horizontal (lateral), no utilice esta configuración.',
      en_rules: 'Only use when EMA 20/50 is clearly sloping. If the EMA is horizontal (Sideway), do not use this setup.',
      riskLevel: 'Trung Bình',
      zh_riskLevel: '中',
      ko_riskLevel: '보통',
      es_riskLevel: 'Medio',
      en_riskLevel: 'Medium',
      color: 'text-emerald-400 border-emerald-500/30 bg-emerald-500/10'
    },
    {
      tag: '#Setup_TrendlineTouch',
      label: 'Chạm Đường Trendline Xu Hướng',
      zh_label: '触及趋势线 趋势线',
      ko_label: '추세선 추세선 터치',
      es_label: 'Tocando la línea de tendencia Línea de tendencia',
      en_label: 'Touching the Trend Line Trendline',
      category: 'setups',
      group: 'Thuận Wave (Trend Following)',
      zh_group: '顺势交易 (Trend Following)',
      ko_group: '추세 추종 (Trend Following)',
      es_group: 'Seguimiento de Tendencia',
      en_group: 'Trend Following',
      description: 'Giá quay lại chạm đường Trendline chéo nối các đỉnh/đáy trước đó và xuất hiện tín hiệu đảo chiều từ chối giá tiếp diễn theo sóng.',
      zh_description: '价格回到触及连接先前峰值/底部的对角趋势线，出现反转信号，否认价格继续在波浪中。',
      ko_description: '가격은 이전 고점/저점을 연결하는 대각선 추세선을 터치하기 위해 되돌아왔고 반전 신호가 나타나 가격이 계속되는 파동을 거부했습니다.',
      es_description: 'El precio volvió a tocar la línea de tendencia diagonal que conecta los picos/fondos anteriores y apareció una señal de reversión, negando que el precio continuara en la onda.',
      en_description: 'The price returned to touch the diagonal Trendline connecting the previous peaks/bottoms and a reversal signal appeared, denying the price continuing in the wave.',
      rules: 'Trendline hiệu quả nhất ở lần chạm thứ 2 và thứ 3. Lần chạm thứ 4 trở đi có nguy cơ gãy đứt Trendline rất cao.',
      zh_rules: '趋势线在第二次和第三次触及时最有效。第四次触及之后突破趋势线的风险非常高。',
      ko_rules: '추세선은 2번째와 3번째 터치에서 가장 효과적입니다. 4번째 터치 이후에는 추세선을 깨뜨릴 위험이 매우 높습니다.',
      es_rules: 'Trendline es más eficaz en el segundo y tercer toque. El 4º toque en adelante tiene un riesgo muy alto de romper la Línea de Tendencia.',
      en_rules: 'Trendline is most effective at the 2nd and 3rd touches. The 4th touch onwards has a very high risk of breaking the Trendline.',
      riskLevel: 'Trung Bình',
      zh_riskLevel: '中',
      ko_riskLevel: '보통',
      es_riskLevel: 'Medio',
      en_riskLevel: 'Medium',
      color: 'text-emerald-400 border-emerald-500/30 bg-emerald-500/10'
    },
    {
      tag: '#Setup_SWRange',
      label: 'Đánh Biển Biên Khung Sideway',
      zh_label: '标记侧向框架边框标志',
      ko_label: '마크 옆쪽 프레임 테두리 표시',
      es_label: 'Marcar signo de borde de marco lateral',
      en_label: 'Mark Sideway Frame Border Sign',
      category: 'setups',
      group: 'Đảo Chiều / Range',
      zh_group: '反转 / 震荡 (Reversal / Range)',
      ko_group: '반전 / 횡보 (Reversal / Range)',
      es_group: 'Reversión / Rango',
      en_group: 'Reversal / Range',
      description: 'Giao dịch đảo chiều biên độ ngắn tại 2 đường biên Kháng cự trên và Hỗ trợ dưới của khung đi ngang (Range Bound / Rectangle Pattern).',
      zh_description: '在水平框架的上阻力和下支撑边界处进行短期反转交易（区间/矩形模式）。',
      ko_description: '수평 프레임(범위 경계/직사각형 패턴)의 상단 저항 및 하단 지지 경계에서 단거리 반전 거래.',
      es_description: 'Comercio de reversión de corto alcance en los límites de resistencia superior y soporte inferior del marco horizontal (Patrón de límite de rango/rectángulo).',
      en_description: 'Short-range reversal trading at the Upper Resistance and Lower Support borders of the horizontal frame (Range Bound / Rectangle Pattern).',
      rules: 'Sell tại Biên Trên, Buy tại Biên Dưới. SL đặt ngoài vùng biên 10-15 pips. Chốt lời TP tại biên đối diện hoặc Đường Trung Vị (Midline).',
      zh_rules: '在上边界卖出，在下边界买入。止损位于边界区域外 10-15 点。在相反的边界或中线获取目标价利润。',
      ko_rules: '상단 국경에서 판매, 하단 국경에서 구매. SL은 국경 구역 바깥쪽 10-15핍에 배치됩니다. 반대쪽 국경이나 미드라인에서 TP 수익을 얻으세요.',
      es_rules: 'Vender en el borde superior, comprar en el borde inferior. SL se coloca entre 10 y 15 pips fuera de la zona fronteriza. Tome la ganancia de TP en el borde opuesto o en la línea media.',
      en_rules: 'Sell ​​at the Upper Border, Buy at the Lower Border. SL is placed 10-15 pips outside the border zone. Take TP profit at the opposite border or Midline.',
      riskLevel: 'Trung Bình',
      zh_riskLevel: '中',
      ko_riskLevel: '보통',
      es_riskLevel: 'Medio',
      en_riskLevel: 'Medium',
      color: 'text-teal-400 border-teal-500/30 bg-teal-500/10'
    },
    {
      tag: '#Setup_LiquiditySweep',
      label: 'Quét Thanh Khoản (Sweep / Fakeout)',
      zh_label: '扫一扫/假出',
      ko_label: '스윕/페이크아웃',
      es_label: 'Barrido / Falsificación',
      en_label: 'Sweep / Fakeout',
      category: 'setups',
      group: 'Đảo Chiều / Range',
      zh_group: '反转 / 震荡 (Reversal / Range)',
      ko_group: '반전 / 횡보 (Reversal / Range)',
      es_group: 'Reversión / Rango',
      en_group: 'Reversal / Range',
      description: 'Cú đâm râu nến qua đỉnh/đáy cứng để cắn Stop Loss của số đông đám đông (Stop Hunt), sau đó đóng nến rút chân ngắt quãng đảo chiều cực kỳ nhanh.',
      zh_description: '蜡烛线冲破硬顶/底部，咬住人群的止损位（Stop Hunt），然后关闭蜡烛并撤回腿，以很快打断反转。',
      ko_description: '캔들 심지가 단단한 상단/하단을 뚫고 충돌하여 군중의 Stop Loss(Stop Hunt)를 물린 다음 캔들을 닫고 다리를 철수하여 반전을 매우 빠르게 중단합니다.',
      es_description: 'La mecha de la vela atraviesa la parte superior/inferior dura para morder el Stop Loss (Stop Hunt) de la multitud, luego cierra la vela y retira las piernas para interrumpir la reversión muy rápidamente.',
      en_description: 'The candle wick crashes through the hard top/bottom to bite the crowd\'s Stop Loss (Stop Hunt), then closes the candle and withdraws the legs to interrupt the reversal very quickly.',
      rules: 'Đợi nến M5 đâm thủng cản rồi đóng cửa ngược lại hoàn toàn vào bên trong vùng giá cũ mới bấm lệnh.',
      zh_rules: '等待 M5 蜡烛突破阻力位，然后完全收盘回到旧价格范围内，然后再下订单。',
      ko_rules: 'M5 양초가 저항선을 뚫을 때까지 기다린 다음 주문을 누르기 전에 이전 가격 범위 내로 완전히 닫힙니다.',
      es_rules: 'Espere a que la vela M5 penetre la resistencia y luego se cierre completamente dentro del rango de precios anterior antes de presionar la orden.',
      en_rules: 'Wait for the M5 candle to penetrate the resistance and then close completely back inside the old price range before pressing the order.',
      riskLevel: 'Trung Bình',
      zh_riskLevel: '中',
      ko_riskLevel: '보통',
      es_riskLevel: 'Medio',
      en_riskLevel: 'Medium',
      color: 'text-teal-400 border-teal-500/30 bg-teal-500/10'
    },
    {
      tag: '#Setup_SupportBounce',
      label: 'Bật Nền Hỗ Trợ Đáy Cứng',
      zh_label: '打开硬底支撑平台',
      ko_label: '단단한 바닥 지지 플랫폼 켜기',
      es_label: 'Encienda la plataforma de soporte de fondo duro',
      en_label: 'Turn on the Hard Bottom Support Platform',
      category: 'setups',
      group: 'Đảo Chiều / Range',
      zh_group: '反转 / 震荡 (Reversal / Range)',
      ko_group: '반전 / 횡보 (Reversal / Range)',
      es_group: 'Reversión / Rango',
      en_group: 'Reversal / Range',
      description: 'Mua bắt phản ứng nến rút chân tăng giá khi chạm vào Vùng Hỗ Trợ cứng đã được kiểm chứng nhiều lần trong quá khứ.',
      zh_description: '过去已经多次证明，在触及硬支撑区时买入以捕捉看涨回撤烛台的反应。',
      ko_description: '하드 지지대를 터치할 때 강세 캔들스틱의 철수 반응을 잡기 위해 매수하는 것은 과거에 여러 번 입증되었습니다.',
      es_description: 'Comprar para captar la reacción de la vela de retirada alcista cuando toca la zona de soporte dura se ha demostrado muchas veces en el pasado.',
      en_description: 'Buying to catch the reaction of the bullish withdrawal candlestick when touching the hard Support Zone has been proven many times in the past.',
      rules: 'Cần xác nhận mô hình nến đảo chiều (Pinbar tăng, Nến Nhấn Chìm Tăng Bullish Engulfing). SL dưới cản cứng 10 pips.',
      zh_rules: '需要确认烛台反转形态（看涨吞没 Pinbar、看涨吞没蜡烛）。止损低于硬屏障 10 点。',
      ko_rules: '캔들스틱 반전 패턴(Bullish Engulfing Pinbar, Bullish Engulfing Candle)을 확인해야 합니다. 하드 배리어 10핍 이하의 SL.',
      es_rules: 'Es necesario confirmar el patrón de inversión de velas (Pinbar envolvente alcista, vela envolvente alcista). SL por debajo de la barrera dura 10 pips.',
      en_rules: 'Need to confirm the candlestick reversal pattern (Bullish Engulfing Pinbar, Bullish Engulfing Candle). SL below hard barrier 10 pips.',
      riskLevel: 'Trung Bình',
      zh_riskLevel: '中',
      ko_riskLevel: '보통',
      es_riskLevel: 'Medio',
      en_riskLevel: 'Medium',
      color: 'text-teal-400 border-teal-500/30 bg-teal-500/10'
    },
    {
      tag: '#Setup_ResistanceReject',
      label: 'Từ Chối Kháng Cự Đỉnh Cứng',
      zh_label: '拒绝硬顶阻力',
      ko_label: '하드탑 저항 거부',
      es_label: 'Rechazo de la resistencia del techo rígido',
      en_label: 'Rejection of Hard Top Resistance',
      category: 'setups',
      group: 'Đảo Chiều / Range',
      zh_group: '反转 / 震荡 (Reversal / Range)',
      ko_group: '반전 / 횡보 (Reversal / Range)',
      es_group: 'Reversión / Rango',
      en_group: 'Reversal / Range',
      description: 'Bán đảo chiều khi nến tiến sát Vùng Kháng Cự / Đỉnh cũ bị từ chối giá (Shooting Star / Bearish Engulfing).',
      zh_description: '当蜡烛接近阻力区/旧高点被价格拒绝时卖出反转（流星/看跌吞没）。',
      ko_description: '캔들이 저항권에 접근하면 매도 반전 / Old Peak가 가격에 의해 거부됩니다 (Shooting Star / Bearish Engulfing).',
      es_description: 'La reversión de venta cuando la vela se acerca a la zona de resistencia / pico antiguo es rechazada por el precio (estrella fugaz / envolvente bajista).',
      en_description: 'Sell ​​reversal when the candlestick approaches the Resistance Zone / Old Peak is rejected by the price (Shooting Star / Bearish Engulfing).',
      rules: 'Không bán khi cây nến tiến tới là nến Marubozu xanh lực đẩy quá mạnh. Chỉ Sell khi có nến từ chối có râu trên dài.',
      zh_rules: '当蜡烛接近时不要卖出。绿色丸子烛的推动力太强了。仅当存在带有长上影线的拒绝蜡烛时才卖出。',
      ko_rules: '양초가 다가올 때 팔지 마십시오. 녹색 마루보즈 캔들의 밀기가 너무 강합니다. 위쪽 심지가 긴 리젝션 캔들이 있는 경우에만 판매하세요.',
      es_rules: 'No vender cuando se acerque la vela. El empuje de la vela verde Marubozu es demasiado fuerte. Vender sólo cuando haya una vela de rechazo con una mecha superior larga.',
      en_rules: 'Do not sell when the candle approaches. The green Marubozu candle\'s push is too strong. Only Sell when there is a rejection candle with a long upper wick.',
      riskLevel: 'Trung Bình',
      zh_riskLevel: '中',
      ko_riskLevel: '보통',
      es_riskLevel: 'Medio',
      en_riskLevel: 'Medium',
      color: 'text-teal-400 border-teal-500/30 bg-teal-500/10'
    },
    {
      tag: '#Setup_SupplyZone',
      label: 'Phản Ứng Vùng Cung (Supply Zone)',
      zh_label: '供应区响应',
      ko_label: '공급 구역 대응',
      es_label: 'Respuesta de la zona de suministro',
      en_label: 'Supply Zone Response',
      category: 'setups',
      group: 'Đảo Chiều / Range',
      zh_group: '反转 / 震荡 (Reversal / Range)',
      ko_group: '반전 / 횡보 (Reversal / Range)',
      es_group: 'Reversión / Rango',
      en_group: 'Reversal / Range',
      description: 'Đánh phản ứng nến từ chối tại Vùng Cung (Supply Zone - Vùng nén xả hàng bùng nổ giảm trước đó trong SMC/ICT).',
      zh_description: '击中供给区的拒绝烛台反应（供给区 - SMC/ICT 中之前的看跌爆炸性排放压缩区）。',
      ko_description: '공급 구역(공급 구역 - SMC/ICT의 이전 약세 폭발물 방전 압축 구역)에서 거부 캔들스틱 반응을 쳤습니다.',
      es_description: 'Golpee la reacción de la vela de rechazo en la zona de oferta (Zona de oferta: la zona de compresión de descarga explosiva bajista anterior en SMC/ICT).',
      en_description: 'Hit the rejection candlestick reaction in the Supply Zone (Supply Zone - The previous bearish explosive discharge compression zone in SMC/ICT).',
      rules: 'Xác định vùng Order Block (OB) hoặc Drop-Base-Drop sạch chưa bị khai thác (Unmitigated).',
      zh_rules: '识别未被利用（未缓解）的干净订单块 (OB) 或 Drop-Base-Drop 区域。',
      ko_rules: '악용되지 않은 깨끗한 OB(Order Block) 또는 Drop-Base-Drop 영역을 식별합니다(완화되지 않음).',
      es_rules: 'Identifique un bloque de órdenes (OB) limpio o un área de caída-base-caída que no haya sido explotada (sin mitigar).',
      en_rules: 'Identify a clean Order Block (OB) or Drop-Base-Drop area that has not been exploited (Unmitigated).',
      riskLevel: 'Trung Bình',
      zh_riskLevel: '中',
      ko_riskLevel: '보통',
      es_riskLevel: 'Medio',
      en_riskLevel: 'Medium',
      color: 'text-teal-400 border-teal-500/30 bg-teal-500/10'
    },
    {
      tag: '#Setup_DemandZone',
      label: 'Phản Ứng Vùng Cầu (Demand Zone)',
      zh_label: '需求区响应',
      ko_label: '수요지역 대응',
      es_label: 'Respuesta de la zona de demanda',
      en_label: 'Demand Zone Response',
      category: 'setups',
      group: 'Đảo Chiều / Range',
      zh_group: '反转 / 震荡 (Reversal / Range)',
      ko_group: '반전 / 횡보 (Reversal / Range)',
      es_group: 'Reversión / Rango',
      en_group: 'Reversal / Range',
      description: 'Đánh phản ứng nến bật giá tại Vùng Cầu (Demand Zone - Vùng nén gom hàng bùng nổ tăng trước đó).',
      zh_description: '检查烛台反应以调高需求区域中的价格（需求区域 - 压缩区域以收集之前的爆炸性上涨）。',
      ko_description: '수요존(수요존 - 이전 폭발적 상승을 수집하는 압축존)의 가격을 올리려면 캔들스틱 반응을 확인하세요.',
      es_description: 'Compruebe la reacción de la vela para subir el precio en la zona de demanda (zona de demanda - zona de compresión para recoger el aumento explosivo anterior).',
      en_description: 'Check the candlestick reaction to turn up the price in the Demand Zone (Demand Zone - Compression zone to collect the previous explosive increase).',
      rules: 'Chỉ đánh vùng Cầu tươi mới chưa bị chạm nhiều lần (Fresh OB). SL đặt ngay sau đáy Vùng Cầu.',
      zh_rules: '只攻击未曾多次触及的新鲜桥区（新鲜OB）。 SL 位于需求区底部的正后方。',
      ko_rules: '여러 번 접촉하지 않은 신선한 다리 지역만 공격하세요(신선한 OB). SL은 수요존 하단 바로 뒤에 위치합니다.',
      es_rules: 'Solo ataca áreas nuevas del Puente que no hayan sido tocadas muchas veces (OB fresco). SL se coloca justo detrás de la parte inferior de la Zona de Demanda.',
      en_rules: 'Only attack fresh Bridge areas that have not been touched many times (Fresh OB). SL is placed right behind the bottom of the Demand Zone.',
      riskLevel: 'Trung Bình',
      zh_riskLevel: '中',
      ko_riskLevel: '보통',
      es_riskLevel: 'Medio',
      en_riskLevel: 'Medium',
      color: 'text-teal-400 border-teal-500/30 bg-teal-500/10'
    },
    {
      tag: '#Setup_DoubleTop',
      label: 'Mô hình 2 Đỉnh (M-Pattern)',
      zh_label: '2 峰模型（M 型）',
      ko_label: '2 피크 모델(M 패턴)',
      es_label: 'Modelo de 2 picos (patrón M)',
      en_label: '2 Peaks Model (M-Pattern)',
      category: 'setups',
      group: 'Đảo Chiều / Range',
      zh_group: '反转 / 震荡 (Reversal / Range)',
      ko_group: '반전 / 횡보 (Reversal / Range)',
      es_group: 'Reversión / Rango',
      en_group: 'Reversal / Range',
      description: 'Mô hình 2 Đỉnh (M) thể hiện phe mua cạn lực ở đỉnh thứ 2 không tạo được đỉnh cao hơn, chuẩn bị đảo chiều giảm.',
      zh_description: '双峰模型（M）显示，买家在第二个峰值时已经耗尽了力量，无法创造更高的峰值，准备逆转下行。',
      ko_description: '2 Peaks 모델(M)은 구매자가 두 번째 고점에서 힘을 다 써버리고 더 높은 고점을 만들지 못하고 하락 반전을 준비하는 모습을 보여줍니다.',
      es_description: 'El modelo de los 2 picos (M) muestra que los compradores han agotado sus fuerzas en el segundo pico y no pueden crear un pico más alto, preparándose para revertir a la baja.',
      en_description: 'The 2 Peaks model (M) shows that buyers have exhausted their strength at the second peak and cannot create a higher peak, preparing to reverse to the downside.',
      rules: 'Có 2 cách đánh: Bắt đỉnh 2 có phân kỳ RSI/MACD hoặc Đợi gãy Đường Cổ (Neckline) rồi Sell tại nhịp retest.',
      zh_rules: '有 2 种玩法：利用 RSI/MACD 背离捕捉峰值 2 或等待颈线突破，然后在重新测试时卖出。',
      ko_rules: '플레이하는 방법에는 2가지가 있습니다. RSI/MACD 다이버전스가 있는 피크 2를 잡거나 넥라인이 무너질 때까지 기다렸다가 재테스트에서 매도하는 것입니다.',
      es_rules: 'Hay 2 formas de jugar: alcanzar el pico 2 con divergencia RSI/MACD o esperar a que se rompa el escote y luego vender en la nueva prueba.',
      en_rules: 'There are 2 ways to play: Catch peak 2 with RSI/MACD divergence or Wait for the Neckline to break and then Sell at the retest.',
      riskLevel: 'Trung Bình',
      zh_riskLevel: '中',
      ko_riskLevel: '보통',
      es_riskLevel: 'Medio',
      en_riskLevel: 'Medium',
      color: 'text-teal-400 border-teal-500/30 bg-teal-500/10'
    },
    {
      tag: '#Setup_DoubleBottom',
      label: 'Mô hình 2 Đáy (W-Pattern)',
      zh_label: '2 底图案（W 图案）',
      ko_label: '2-바닥 패턴(W-패턴)',
      es_label: 'Patrón de 2 fondos (patrón W)',
      en_label: '2-Bottom Pattern (W-Pattern)',
      category: 'setups',
      group: 'Đảo Chiều / Range',
      zh_group: '反转 / 震荡 (Reversal / Range)',
      ko_group: '반전 / 횡보 (Reversal / Range)',
      es_group: 'Reversión / Rango',
      en_group: 'Reversal / Range',
      description: 'Mô hình 2 Đáy (W) thể hiện phe bán kiệt sức tại đáy thứ 2, tạo nền bệ đỡ tăng giá.',
      zh_description: '第二个底部 (W) 模型表明，卖家在第二个底部已经筋疲力尽，从而创建了一个支持价格上涨的平台。',
      ko_description: '2바텀(W) 모델은 2차 바텀에서 판매자가 지쳐가는 모습을 보여주며, 가격 인상을 뒷받침할 수 있는 플랫폼을 만들어준다.',
      es_description: 'El modelo 2 Bottom (W) muestra que los vendedores están agotados en el segundo piso, creando una plataforma para respaldar los aumentos de precios.',
      en_description: 'The 2 Bottom (W) model shows that sellers are exhausted at the 2nd bottom, creating a platform to support price increases.',
      rules: 'Ưu tiên đáy 2 tạo rút chân mạnh hoặc phân kỳ tăng giá. SL ngay dưới đáy 2.',
      zh_rules: '优先考虑底部 2 点以创造强劲回撤或看涨背离。 SL 位于底部 2 正下方。',
      ko_rules: '강력한 철수 또는 강세 다이버전스를 생성하려면 하위 2개 항목에 우선순위를 둡니다. 하단 2 바로 아래 SL.',
      es_rules: 'Priorice los 2 últimos para crear fuertes retiros o divergencia alcista. SL justo debajo del fondo 2.',
      en_rules: 'Prioritize bottom 2 to create strong withdrawals or bullish divergence. SL right below bottom 2.',
      riskLevel: 'Trung Bình',
      zh_riskLevel: '中',
      ko_riskLevel: '보통',
      es_riskLevel: 'Medio',
      en_riskLevel: 'Medium',
      color: 'text-teal-400 border-teal-500/30 bg-teal-500/10'
    },
    {
      tag: '#Setup_FairValueGap',
      label: 'Lấp Khoảng Trống FVG (Imbalance)',
      zh_label: '填补空白 FVG（不平衡）',
      ko_label: '격차 FVG 채우기(불균형)',
      es_label: 'Llenar el vacío FVG (desequilibrio)',
      en_label: 'Fill the Gap FVG (Imbalance)',
      category: 'setups',
      group: 'Đảo Chiều / Range',
      zh_group: '反转 / 震荡 (Reversal / Range)',
      ko_group: '반전 / 횡보 (Reversal / Range)',
      es_group: 'Reversión / Rango',
      en_group: 'Reversal / Range',
      description: 'Đánh nhịp giá hồi về lấp khoảng trống mất cân bằng cung cầu (Fair Value Gap - FVG 3 nến) trước khi tiếp diễn sóng.',
      zh_description: '在继续波浪之前，检查回调是否会填补供需失衡（公允价值缺口 - FVG 3 根蜡烛）。',
      ko_description: '파동을 계속하기 전에 수요-공급 불균형(공정 가치 격차 - FVG 3 양초)을 메우기 위한 하락세를 확인하세요.',
      es_description: 'Compruebe si hay un retroceso para compensar el desequilibrio entre oferta y demanda (Brecha de valor razonable - FVG 3 velas) antes de continuar la ola.',
      en_description: 'Check for a pullback to fill the supply-demand imbalance (Fair Value Gap - FVG 3 candles) before continuing the wave.',
      rules: 'Cần kết hợp FVG nằm trùng với vùng Keylevel / OTE (Fibonacci 0.618 - 0.786) để nâng Winrate.',
      zh_rules: '需要将 FVG 与 Keylevel / OTE 区域（斐波那契 0.618 - 0.786）结合起来以提高胜率。',
      ko_rules: 'Winrate를 높이려면 Keylevel/OTE 영역(Fibonacci 0.618 - 0.786)과 일치하도록 FVG를 결합해야 합니다.',
      es_rules: 'Es necesario combinar FVG para que coincida con el área Keylevel/OTE (Fibonacci 0,618 - 0,786) para aumentar Winrate.',
      en_rules: 'Need to combine FVG to coincide with the Keylevel / OTE area (Fibonacci 0.618 - 0.786) to increase Winrate.',
      riskLevel: 'Trung Bình',
      zh_riskLevel: '中',
      ko_riskLevel: '보통',
      es_riskLevel: 'Medio',
      en_riskLevel: 'Medium',
      color: 'text-teal-400 border-teal-500/30 bg-teal-500/10'
    },
    {
      tag: '#scalp',
      label: 'Giao Dịch Scalping Nhanh',
      zh_label: '快速倒卖交易',
      ko_label: '빠른 스캘핑 트레이딩',
      es_label: 'Comercio de especulación rápida',
      en_label: 'Fast Scalping Trading',
      category: 'setups',
      group: 'Scalping Nhanh',
      zh_group: '快速倒卖',
      ko_group: '빠른 스캘핑',
      es_group: 'Scalping rápido',
      en_group: 'Fast Scalping',
      description: 'Giao dịch lướt sóng nhanh trong khung M1/M5, chốt lời ngắn (15-30 pips) và quản lý rủi ro siêu chặt.',
      zh_description: 'M1/M5 框架内的快速波动交易、空头获利了结（15-30 点）和超严格的风险管理。',
      ko_description: 'M1/M5 프레임의 빠른 스윙 트레이딩, 단기 이익 실현(15-30핍) 및 매우 엄격한 위험 관리.',
      es_description: 'Comercio de swing rápido en el marco M1/M5, toma de ganancias corta (15-30 pips) y gestión de riesgos súper estricta.',
      en_description: 'Fast swing trading in the M1/M5 frame, short profit taking (15-30 pips) and super tight risk management.',
      rules: 'Phải tuân thủ SL cứng tuyệt đối. Không gồng lệnh scalp qua đêm hoặc giữ lệnh khi ra tin.',
      zh_rules: '必须遵守绝对严格的 SL。不要持有剥头皮订单过夜或在消息发布时持有订单。',
      ko_rules: '절대 하드 SL을 준수해야 합니다. 밤새 두피 주문을 보류하거나 뉴스가 발표되었을 때 주문을 보류하지 마십시오.',
      es_rules: 'Debe cumplir con SL absolutamente duro. No retenga órdenes de cuero cabelludo durante la noche ni retenga órdenes cuando se publiquen noticias.',
      en_rules: 'Must adhere to absolute hard SL. Do not hold scalp orders overnight or hold orders when news is released.',
      riskLevel: 'Cao',
      zh_riskLevel: '高',
      ko_riskLevel: '높음',
      es_riskLevel: 'Alto',
      en_riskLevel: 'High',
      color: 'text-indigo-400 border-indigo-500/30 bg-indigo-500/10'
    },
  ],

  trends: [
    {
      tag: '#Trend_Bullish',
      label: 'Xu Hướng Tăng (Bullish)',
      zh_label: '看涨趋势',
      ko_label: '강세 추세',
      es_label: 'Tendencia alcista',
      en_label: 'Bullish Trend',
      category: 'trends',
      group: 'Xu Hướng Thị Trường',
      zh_group: '市场趋势',
      ko_group: '시장 동향',
      es_group: 'Tendencias del mercado',
      en_group: 'Market Trends',
      description: 'Cấu trúc thị trường Tăng rõ ràng: Đỉnh sau cao hơn đỉnh trước (Higher High - HH) & Đáy sau cao hơn đáy trước (Higher Low - HL).',
      zh_description: '市场结构 明显增加：下一个峰值高于前一个峰值（更高的高点 - HH），下一个底部高于前一个底部（更高的低点 - HL）。',
      ko_description: '시장 구조 뚜렷한 증가세: 다음 고점은 이전 고점보다 높고(Higher High - HH) 다음 저점은 이전 저점보다 높습니다(Higher Low - HL).',
      es_description: 'Estructura del mercado Claramente en aumento: el siguiente pico es más alto que el pico anterior (máximo más alto - HH) y el siguiente mínimo es más alto que el mínimo anterior (mínimo más alto - HL).',
      en_description: 'Market structure Clearly increasing: The next peak is higher than the previous peak (Higher High - HH) & The next bottom is higher than the previous bottom (Higher Low - HL).',
      rules: 'Chỉ ưu tiên CANH MUA (BUY ON DIPS) tại các vùng Higher Low. Hạn chế Sell cản.',
      zh_rules: '仅优先在较高低点区域逢低买入。限制销售障碍。',
      ko_rules: '더 높은 저점 지역의 DIPS 매수에만 우선순위가 부여됩니다. 판매 장벽을 제한하십시오.',
      es_rules: 'Solo se da prioridad a COMPRAR EN DIPS en las regiones más altas y bajas. Limitar las barreras de venta.',
      en_rules: 'Priority is only given to BUY ON DIPS in Higher Low regions. Limit Selling barriers.',
      riskLevel: 'Thấp',
      zh_riskLevel: '低',
      ko_riskLevel: '낮음',
      es_riskLevel: 'Bajo',
      en_riskLevel: 'Low',
      color: 'text-emerald-400 border-emerald-500/30 bg-emerald-500/10'
    },
    {
      tag: '#Trend_Bearish',
      label: 'Xu Hướng Giảm (Bearish)',
      zh_label: '看跌趋势',
      ko_label: '약세 추세',
      es_label: 'Tendencia bajista',
      en_label: 'Bearish Trend',
      category: 'trends',
      group: 'Xu Hướng Thị Trường',
      zh_group: '市场趋势',
      ko_group: '시장 동향',
      es_group: 'Tendencias del mercado',
      en_group: 'Market Trends',
      description: 'Cấu trúc thị trường Giảm rõ ràng: Đỉnh sau thấp hơn đỉnh trước (Lower High - LH) & Đáy sau thấp hơn đáy trước (Lower Low - LL).',
      zh_description: '市场结构明显看跌：下一个峰值低于前一个峰值（较低高点 - LH），下一个底部低于前一个底部（较低低点 - LL）。',
      ko_description: '시장 구조는 확실히 약세입니다. 다음 고점은 이전 고점(낮은 고점 - LH)보다 낮고 다음 저점은 이전 저점(낮은 저점 - LL)보다 낮습니다.',
      es_description: 'La estructura del mercado es claramente bajista: el siguiente pico es más bajo que el pico anterior (máximo inferior - LH) y el siguiente mínimo es más bajo que el mínimo anterior (mínimo inferior - LL).',
      en_description: 'Market structure is clearly Bearish: The next peak is lower than the previous peak (Lower High - LH) & The next bottom is lower than the previous bottom (Lower Low - LL).',
      rules: 'Chỉ ưu tiên CANH BÁN (SELL ON RALLIES) tại các điểm Lower High.',
      zh_rules: '仅在较低高点时优先逢高卖出。',
      ko_rules: '낮은 고점에서만 RALLIES 판매에 우선권이 부여됩니다.',
      es_rules: 'Se da prioridad a VENDER EN RALLIES sólo en los puntos más bajos.',
      en_rules: 'Priority is given to SELL ON RALLIES only at Lower High points.',
      riskLevel: 'Thấp',
      zh_riskLevel: '低',
      ko_riskLevel: '낮음',
      es_riskLevel: 'Bajo',
      en_riskLevel: 'Low',
      color: 'text-rose-400 border-rose-500/30 bg-rose-500/10'
    },
    {
      tag: '#Trend_Sideway',
      label: 'Thị Trường Đi Ngang (Sideway)',
      zh_label: '横向市场',
      ko_label: '사이드웨이 마켓',
      es_label: 'Mercado lateral',
      en_label: 'Sideways Market',
      category: 'trends',
      group: 'Xu Hướng Thị Trường',
      zh_group: '市场趋势',
      ko_group: '시장 동향',
      es_group: 'Tendencias del mercado',
      en_group: 'Market Trends',
      description: 'Giá di chuyển nén ngang trong vùng biên độ hẹp, chưa hình thành xu hướng tăng/giảm rõ nét.',
      zh_description: '价格窄幅横盘走势，未形成明显的上涨/下跌趋势。',
      ko_description: '가격은 명확한 상승/하락 추세를 형성하지 않고 좁은 범위에서 수평으로 움직입니다.',
      es_description: 'El precio se mueve horizontalmente en un rango estrecho, sin formar una tendencia clara hacia arriba o hacia abajo.',
      en_description: 'The price moves horizontally in a narrow range, not forming a clear up/down trend.',
      rules: 'Đánh lướt tại 2 biên hoặc đứng ngoài kiên nhẫn chờ cú bứt phá vỡ biên (Breakout).',
      zh_rules: '在两个边界滑行或耐心地站在外面等待休息。',
      ko_rules: '양쪽 경계에서 활공하거나 밖에 서서 참을성 있게 휴식을 기다리세요.',
      es_rules: 'Deslízate en ambos límites o quédate afuera esperando pacientemente un descanso.',
      en_rules: 'Glide at both boundaries or stand outside patiently waiting for a break.',
      riskLevel: 'Trung Bình',
      zh_riskLevel: '中',
      ko_riskLevel: '보통',
      es_riskLevel: 'Medio',
      en_riskLevel: 'Medium',
      color: 'text-amber-400 border-amber-500/30 bg-amber-500/10'
    },
    {
      tag: '#Trend_WithTrend',
      label: 'Giao Dịch Thuận Xu Hướng',
      zh_label: '根据趋势进行交易',
      ko_label: '추세에 따른 거래',
      es_label: 'Comercio según la tendencia',
      en_label: 'Trade According to the Trend',
      category: 'trends',
      group: 'Đồng Thuận Cấu Trúc',
      zh_group: '结构性共识',
      ko_group: '구조적 합의',
      es_group: 'Consenso estructural',
      en_group: 'Structural Consensus',
      description: 'Đồng thuận cấu trúc sóng trên cả 3 khung thời gian H1, M15, M5 -> Mang lại Winrate và Tỷ lệ R:R cao nhất!',
      zh_description: '所有 3 个时间框架 H1、M15、M5 上的共识波浪结构 -> 带来最高的胜率和 R:R 比率！',
      ko_description: 'H1, M15, M5 3개 시간 프레임 모두에 대한 합의 파동 구조 -> 가장 높은 승률과 R:R 비율을 제공합니다!',
      es_description: 'Estructura de onda de consenso en los 3 marcos de tiempo H1, M15, M5 -> ¡Ofrece la tasa de ganancia y la relación R:R más altas!',
      en_description: 'Consensus wave structure on all 3 time frames H1, M15, M5 -> Brings the highest Winrate and R:R Ratio!',
      rules: 'Được phép đi đủ volume rủi ro cho phép (1-2%). Đây là loại lệnh chất lượng cao nhất.',
      zh_rules: '允许以完全允许的风险量 (1-2%) 旅行。这是最高质量的订单类型。',
      ko_rules: '허용 가능한 전체 위험량(1-2%)으로 여행하는 것이 허용됩니다. 이것은 최고 품질의 주문 유형입니다.',
      es_rules: 'Se le permite viajar con el volumen de riesgo máximo permitido (1-2%). Este es el tipo de pedido de mayor calidad.',
      en_rules: 'Allowed to travel at full allowable risk volume (1-2%). This is the highest quality order type.',
      riskLevel: 'Thấp',
      zh_riskLevel: '低',
      ko_riskLevel: '낮음',
      es_riskLevel: 'Bajo',
      en_riskLevel: 'Low',
      color: 'text-emerald-400 border-emerald-500/30 bg-emerald-500/10'
    },
    {
      tag: '#Trend_Counter',
      label: 'Giao Dịch Ngược Xu Hướng',
      zh_label: '逆势交易',
      ko_label: '카운터트렌드 트레이딩',
      es_label: 'Comercio contratendencia',
      en_label: 'Counter-Trend Trading',
      category: 'trends',
      group: 'Đồng Thuận Cấu Trúc',
      zh_group: '结构性共识',
      ko_group: '구조적 합의',
      es_group: 'Consenso estructural',
      en_group: 'Structural Consensus',
      description: 'Bắt đáy / bắt đỉnh ngược sóng chính đang chạy mạnh -> Rủi ro gồng lỗ hoặc cháy tài khoản cực kỳ cao!',
      zh_description: '抄底/迎着强劲主浪抄顶 -> 亏损或烧毁账户的风险极高！',
      ko_description: '강력한 본류에 맞서 바닥 잡기/고점 잡기 -> 손실을 입거나 계정이 소각될 위험이 매우 높습니다!',
      es_description: 'Atrapar el fondo / atrapar la cima contra la fuerte ola principal -> ¡Riesgo extremadamente alto de sufrir pérdidas o quemar su cuenta!',
      en_description: 'Catching the bottom / catching the top against the strong main wave -> Extremely high risk of making losses or burning your account!',
      rules: 'Giảm 50% khối lượng volume thông thường. Chỉ chốt TP ngắn 1:1 hoặc 1:1.5. Kéo SL về BE ngay khi có lời.',
      zh_rules: '正常音量减少 50%。仅以 1:1 或 1:1.5 平仓 TP。一旦有盈利就将SL拉至BE。',
      ko_rules: '정상 볼륨이 50% 감소합니다. TP를 1:1 또는 1:1.5로 짧게 닫으세요. 이익이 나는 즉시 SL을 BE로 끌어옵니다.',
      es_rules: 'Reducción del 50% del volumen normal. Sólo cierre TP corto 1:1 o 1:1,5. Llevar SL a BE tan pronto como haya ganancias.',
      en_rules: '50% reduction in normal volume. Only close TP short 1:1 or 1:1.5. Pull SL to BE as soon as there is a profit.',
      riskLevel: 'Rất Cao',
      zh_riskLevel: '非常高',
      ko_riskLevel: '매우 높음',
      es_riskLevel: 'muy alto',
      en_riskLevel: 'Very High',
      color: 'text-rose-400 border-rose-500/30 bg-rose-500/10'
    },
    {
      tag: '#Trend_Reversal',
      label: 'Tín Hiệu Đảo Chiều Cấu Trúc',
      zh_label: '结构性反转信号',
      ko_label: '구조적 반전 신호',
      es_label: 'Señal de reversión estructural',
      en_label: 'Structural Reversal Signal',
      category: 'trends',
      group: 'Đồng Thuận Cấu Trúc',
      zh_group: '结构性共识',
      ko_group: '구조적 합의',
      es_group: 'Consenso estructural',
      en_group: 'Structural Consensus',
      description: 'Có tín hiệu gãy cấu trúc xu hướng (ChoCH - Change of Character / BOS - Break of Structure).',
      zh_description: '趋势结构出现突破信号（ChoCH - 性格变化/BOS - 结构突破）。',
      ko_description: '추세 구조(ChoCH - 문자 변경/BOS - 구조 중단)에 중단 신호가 있습니다.',
      es_description: 'Hay una señal de ruptura en la estructura de tendencia (ChoCH - Cambio de Carácter / BOS - Ruptura de Estructura).',
      en_description: 'There is a signal of a break in the trend structure (ChoCH - Change of Character / BOS - Break of Structure).',
      rules: 'Chờ giá quay lại retest điểm gãy cấu trúc ChoCH mới bấm lệnh đảo chiều.',
      zh_rules: '等待价格返回以重新测试 ChoCH 结构突破点，然后再按下反转订单。',
      ko_rules: '반전 주문을 누르기 전에 ChoCH 구조 중단점을 다시 테스트하기 위해 가격이 돌아올 때까지 기다리십시오.',
      es_rules: 'Espere a que el precio regrese para volver a probar el punto de ruptura estructural de ChoCH antes de presionar una orden de reversión.',
      en_rules: 'Wait for the price to return to retest the ChoCH structural break point before pressing a reversal order.',
      riskLevel: 'Trung Bình',
      zh_riskLevel: '中',
      ko_riskLevel: '보통',
      es_riskLevel: 'Medio',
      en_riskLevel: 'Medium',
      color: 'text-indigo-400 border-indigo-500/30 bg-indigo-500/10'
    },
  ],

  mistakes: [
    {
      tag: '#Mistake_DCA',
      label: 'Nhồi Lệnh Lỗ (DCA Âm / Martingale)',
      zh_label: '填充损失订单（负 DCA / Martingale）',
      ko_label: '스터핑 손실 순서(음성 DCA/마틴게일)',
      es_label: 'Orden de pérdida de relleno (DCA negativo/martingala)',
      en_label: 'Stuffing Loss Order (Negative DCA / Martingale)',
      category: 'mistakes',
      group: 'Lỗi Quản Lý Rủi Ro',
      zh_group: '风险管理失败',
      ko_group: '위험 관리 실패',
      es_group: 'Fracaso en la gestión de riesgos',
      en_group: 'Risk Management Failure',
      description: 'Nhồi thêm volume khi lệnh ban đầu đang gồng lỗ với hy vọng giá chỉ cần hồi nhẹ là hòa vốn. Nguyên nhân số 1 dẫn tới Cháy Tài Khoản!',
      zh_description: '当最初的订单亏损时，增加成交量，希望价格只需要稍微恢复即可达到盈亏平衡。帐户被火的第一大原因！',
      ko_description: '가격이 약간 회복되어 손익분기점에 도달하기를 바라면서 초기 주문이 손실을 입었을 때 더 많은 수량을 추가합니다. 계정 화재 원인 1위!',
      es_description: 'Agregar más volumen cuando el pedido inicial tiene pérdidas con la esperanza de que el precio solo necesite recuperarse ligeramente para alcanzar el punto de equilibrio. ¡La causa número uno de incendio de cuentas!',
      en_description: 'Adding more volume when the initial order is at a loss in the hope that the price only needs to recover slightly to break even. The number 1 cause of Account Fire!',
      rules: 'QUY TẮC VÀNG: Không bao giờ nhồi thêm lệnh khi vị thế cũ đang âm tiền! Nếu sai, chấp nhận dính Stop Loss.',
      zh_rules: '黄金法则：当旧头寸处于负数时，切勿添加更多订单！如果错误，接受止损。',
      ko_rules: '황금률: 기존 포지션이 마이너스 금액일 때는 더 이상 주문을 추가하지 마세요! 틀리면 Stop Loss를 수락하세요.',
      es_rules: 'REGLA DE ORO: ¡Nunca agregue más órdenes cuando la posición anterior sea de dinero negativo! Si es incorrecto, acepte Stop Loss.',
      en_rules: 'GOLDEN RULE: Never add more orders when the old position is in negative money! If wrong, accept Stop Loss.',
      riskLevel: 'Rất Cao (Cháy TK)',
      zh_riskLevel: '非常高（TK 火）',
      ko_riskLevel: '매우 높음(TK 화재)',
      es_riskLevel: 'Muy alto (fuego TK)',
      en_riskLevel: 'Very High (TK Fire)',
      color: 'text-rose-400 border-rose-500/30 bg-rose-500/10'
    },
    {
      tag: '#Mistake_FOMO',
      label: 'Sợ Bỏ Lỡ Cơ Hội (FOMO)',
      zh_label: '害怕错过（FOMO）',
      ko_label: '누락에 대한 두려움(FOMO)',
      es_label: 'Miedo a perderse algo (FOMO)',
      en_label: 'Fear of Missing Out (FOMO)',
      category: 'mistakes',
      group: 'Lỗi Tâm Lý',
      zh_group: '心理错误',
      ko_group: '심리적 오류',
      es_group: 'Error psicológico',
      en_group: 'Psychological Error',
      description: 'Nhảy vào bấm lệnh mua/bán đuổi khi thấy nến xanh/đỏ dài ngoãng đã chạy được 30-50 pips xa khỏi điểm Entry chuẩn.',
      zh_description: '当您看到一根长绿色/红色蜡烛距离标准切入点 30-50 点时，请进场并按下买入/卖出订单。',
      ko_description: '표준 진입점에서 30-50핍 떨어진 긴 녹색/빨간색 양초가 보이면 뛰어들어 매수/매도 주문을 누르세요.',
      es_description: 'Salta y presiona órdenes de compra/venta cuando veas una larga vela verde/roja que se haya alejado entre 30 y 50 pips del punto de entrada estándar.',
      en_description: 'Jump in and press buy/sell orders when you see a long green/red candle that has run 30-50 pips away from the standard Entry point.',
      rules: 'Nến đã chạy thì BỎ! Nhắc bản thân: "Thị trường luôn luôn có cơ hội mới, mất tiền mới đáng sợ chứ không mất cơ hội".',
      zh_rules: '如果蜡烛已经耗尽，就将其废除！提醒自己：“市场总是有新的机会，赔钱可怕，而不是失去机会。”',
      ko_rules: '촛불이 꺼졌다면 촛불을 폐지하세요! 기억하세요: "시장에는 항상 새로운 기회가 있습니다. 돈을 잃는 것은 두려운 일이지 기회를 잃는 것이 아닙니다."',
      es_rules: 'Si la vela se ha apagado, ¡abolídela! Recuerde: "El mercado siempre tiene nuevas oportunidades, perder dinero da miedo, no perder oportunidades".',
      en_rules: 'If the candle has run then Abolish it! Remind yourself: "The market always has new opportunities, losing money is scary, not losing opportunities."',
      riskLevel: 'Cao',
      zh_riskLevel: '高',
      ko_riskLevel: '높음',
      es_riskLevel: 'Alto',
      en_riskLevel: 'High',
      color: 'text-rose-400 border-rose-500/30 bg-rose-500/10'
    },
    {
      tag: '#Mistake_RevengeTrade',
      label: 'Giao Dịch Trả Thù Thị Trường',
      zh_label: '市场报复性交易',
      ko_label: '시장 복수 거래',
      es_label: 'Comercio de venganza en el mercado',
      en_label: 'Market Revenge Trading',
      category: 'mistakes',
      group: 'Lỗi Tâm Lý',
      zh_group: '心理错误',
      ko_group: '심리적 오류',
      es_group: 'Error psicológico',
      en_group: 'Psychological Error',
      description: 'Vừa dính Stop Loss cay cú, liền lập tức mở ngay lệnh mới cực to để gỡ gạc lại số tiền vừa mất.',
      zh_description: '当我对止损感到沮丧时，我立即开立了一个新的巨额订单，以拿回我刚刚损失的资金。',
      ko_description: '나는 Stop Loss에 좌절하자마자 방금 잃어버린 돈을 되찾기 위해 즉시 새로운 대규모 주문을 열었습니다.',
      es_description: 'Tan pronto como me frustré con Stop Loss, inmediatamente abrí una orden nueva y enorme para recuperar el dinero que acabo de perder.',
      en_description: 'As soon as I got frustrated with Stop Loss, I immediately opened a new, huge order to get back the money I just lost.',
      rules: 'Dính SL 2 lệnh liên tiếp -> Đóng máy tính 30 phút, đi uống nước hoặc đi dạo để hạ nhiệt tâm lý cay cú.',
      zh_rules: '连续坚持SL 2单 -> 关闭电脑30分钟，去喝水或者去散步消解苦味。',
      ko_rules: 'SL 2주문 연속 고집 -> 30분간 컴퓨터를 닫고 물을 마시거나 산책을 하면서 쓴맛을 식혀보세요.',
      es_rules: 'Cumplir con SL 2 pedidos seguidos -> Cierra el ordenador durante 30 minutos, ve a beber agua o sal a caminar para enfriar el amargor.',
      en_rules: 'Sticking to SL 2 orders in a row -> Close the computer for 30 minutes, go drink water or go for a walk to cool down the bitterness.',
      riskLevel: 'Rất Cao',
      zh_riskLevel: '非常高',
      ko_riskLevel: '매우 높음',
      es_riskLevel: 'muy alto',
      en_riskLevel: 'Very High',
      color: 'text-rose-400 border-rose-500/30 bg-rose-500/10'
    },
    {
      tag: '#Mistake_OverTrade',
      label: 'Giao Dịch Quá Nhiều (Over-trading)',
      zh_label: '过度交易',
      ko_label: '과잉 거래',
      es_label: 'Sobrecomercio',
      en_label: 'Over-trading',
      category: 'mistakes',
      group: 'Lỗi Kỷ Luật',
      zh_group: '纪律错误',
      ko_group: '징계 오류',
      es_group: 'Error disciplinario',
      en_group: 'Disciplinary Error',
      description: 'Bấm lệnh liên tục từ sáng tới đêm, vào những lệnh không đúng setup tiêu chuẩn do ngứa tay.',
      zh_description: '从早到晚不断地压订单，手痒痒的输入不符合标准设置的订单。',
      ko_description: '아침부터 밤까지 계속 주문을 누르고, 손이 가려워 기준에 맞지 않는 주문을 입력한다.',
      es_description: 'Presionar pedidos continuamente desde la mañana hasta la noche, ingresando pedidos que no cumplían con la configuración estándar debido a la picazón en las manos.',
      en_description: 'Pressing orders continuously from morning to night, entering orders that did not meet the standard setup due to itchy hands.',
      rules: 'Giới hạn tối đa 3-5 lệnh/ngày. Hết quota rủi ro trong ngày là dừng tuyệt đối.',
      zh_rules: '每天最多下单 3-5 个。当你当天的风险配额用完时，你就绝对停止了。',
      ko_rules: '하루 최대 주문수량은 3~5개입니다. 하루 동안의 위험 할당량이 소진되면 절대적으로 중지합니다.',
      es_rules: 'Límite máximo de 3-5 pedidos/día. Cuando se agota tu cuota de riesgo del día, te detienes por completo.',
      en_rules: 'Maximum limit of 3-5 orders/day. When your risk quota runs out for the day, you absolutely stop.',
      riskLevel: 'Cao',
      zh_riskLevel: '高',
      ko_riskLevel: '높음',
      es_riskLevel: 'Alto',
      en_riskLevel: 'High',
      color: 'text-rose-400 border-rose-500/30 bg-rose-500/10'
    },
    {
      tag: '#Mistake_OverRisk',
      label: 'Đi Volume Quá Tay (Over-risk)',
      zh_label: '风险过高交易量（风险过高）',
      ko_label: '오버리스크 거래량(오버리스크)',
      es_label: 'Volumen de sobreriesgo (sobreriesgo)',
      en_label: 'Over-risking Volume (Over-risk)',
      category: 'mistakes',
      group: 'Lỗi Quản Lý Rủi Ro',
      zh_group: '风险管理失败',
      ko_group: '위험 관리 실패',
      es_group: 'Fracaso en la gestión de riesgos',
      en_group: 'Risk Management Failure',
      description: 'Vào lot quá lớn so với quy mô tài khoản (ví dụ tài khoản 1,000$ đánh 1.0 lot) khiến tâm lý căng thẳng không gồng nổi.',
      zh_description: '输入与账户规模相比太大的手数（例如，1,000 美元的账户玩 1.0 手）会导致无法克服的心理压力。',
      ko_description: '계좌 규모에 비해 너무 큰 랏을 입력하면(예: $1,000 계좌가 1.0 랏을 플레이함) 극복할 수 없는 심리적 스트레스를 유발합니다.',
      es_description: 'Ingresar un lote que es demasiado grande en comparación con el tamaño de la cuenta (por ejemplo, una cuenta de $1000 juega 1.0 lotes) causa estrés psicológico que no se puede superar.',
      en_description: 'Entering a lot that is too large compared to the account size (for example, a $1,000 account plays 1.0 lots) causes psychological stress that cannot be overcome.',
      rules: 'Cố định mức rủi ro tối đa 1% - 2% tài khoản cho mỗi giao dịch.',
      zh_rules: '每笔交易账户的最大风险水平固定为 1% - 2%。',
      ko_rules: '거래당 계좌의 최대 위험 수준을 1% - 2%로 고정했습니다.',
      es_rules: 'Nivel de riesgo máximo fijo del 1% al 2% de la cuenta por operación.',
      en_rules: 'Fixed maximum risk level of 1% - 2% of account per trade.',
      riskLevel: 'Rất Cao',
      zh_riskLevel: '非常高',
      ko_riskLevel: '매우 높음',
      es_riskLevel: 'muy alto',
      en_riskLevel: 'Very High',
      color: 'text-rose-400 border-rose-500/30 bg-rose-500/10'
    },
    {
      tag: '#Mistake_MovedSL',
      label: 'Dời / Xóa Stop Loss Để Gồng Lỗ',
      zh_label: '移动/删除止损以巩固损失',
      ko_label: '손실을 통합하기 위해 정지 손실 이동/삭제',
      es_label: 'Mover/eliminar Stop Loss para consolidar pérdidas',
      en_label: 'Move / Delete Stop Loss To Consolidate Losses',
      category: 'mistakes',
      group: 'Lỗi Kỷ Luật',
      zh_group: '纪律错误',
      ko_group: '징계 오류',
      es_group: 'Error disciplinario',
      en_group: 'Disciplinary Error',
      description: 'Khi giá tiến sát điểm SL, hoảng sợ kéo SL ra xa hơn hoặc xóa luôn SL với niềm tin mù quáng giá sẽ quay đầu.',
      zh_description: '当价格接近止损点时，恐慌并进一步拉动止损，或者盲目相信价格会反转而删除止损。',
      ko_description: '가격이 SL 지점에 가까워지면 당황하여 SL을 더 당기거나 가격이 반전할 것이라는 맹목적인 믿음으로 SL을 삭제합니다.',
      es_description: 'Cuando el precio se acerque al punto SL, entre en pánico y tire del SL más o elimínelo con la creencia ciega de que el precio cambiará.',
      en_description: 'When the price gets close to the SL point, panic and pull the SL further or delete the SL with the blind belief that the price will turn around.',
      rules: 'Stop Loss là bảo hiểm sinh mạng tài khoản. Đặt SL xong KHÔNG ĐƯỢC KÉO RỘNG NỮA!',
      zh_rules: '止损是账户人寿保险。设置 SL 后，请勿再拉动！',
      ko_rules: 'Stop Loss는 계정 생명 보험입니다. SL을 설정한 후에는 더 이상 당기지 마십시오!',
      es_rules: 'Stop Loss es un seguro de vida de cuenta. Una vez que hayas configurado el SL, ¡NO TIRE MÁS!',
      en_rules: 'Stop Loss is account life insurance. Once you set the SL, DO NOT PULL ANY MORE!',
      riskLevel: 'Rất Cao',
      zh_riskLevel: '非常高',
      ko_riskLevel: '매우 높음',
      es_riskLevel: 'muy alto',
      en_riskLevel: 'Very High',
      color: 'text-rose-400 border-rose-500/30 bg-rose-500/10'
    },
    {
      tag: '#Mistake_GreedHolding',
      label: 'Tham Không Chốt Lời Đúng TP',
      zh_label: '贪婪并不能正确获利 City',
      ko_label: '욕심을 부리면 제대로 이익을 얻지 못한다',
      es_label: 'Ser codicioso no toma ganancias correctamente Ciudad',
      en_label: 'Being Greedy Doesn\'t Take Profit Correctly City',
      category: 'mistakes',
      group: 'Lỗi Tâm Lý',
      zh_group: '心理错误',
      ko_group: '심리적 오류',
      es_group: 'Error psicológico',
      en_group: 'Psychological Error',
      description: 'Lệnh đã đạt TP mục tiêu (+50 pips) nhưng tham gồng thêm, không chốt lời/không chốt một phần để rồi giá quay đầu âm ngược.',
      zh_description: '订单达到目标TP（+50点）但变得更加贪婪，没有获利/没有部分获利，然后价格转负。',
      ko_description: '주문이 목표 TP(+50핍)에 도달했지만 욕심이 더 많아지고 이익을 얻지 못하거나 참여하지 않았으며 가격이 마이너스로 변했습니다.',
      es_description: 'La orden alcanzó el TP objetivo (+50 pips), pero se volvió más codiciosa, no obtuvo ganancias/no participó en ellas, y luego el precio se volvió negativo.',
      en_description: 'The order reached the target TP (+50 pips) but became more greedy, did not take profit/did not take part of it, and then the price turned negative.',
      rules: 'Chốt lời không bao giờ sai! Luôn kéo Stop Loss về Hòa vốn (BE) khi lệnh đã đi được 50% quãng đường tới TP.',
      zh_rules: '获利了结永远不会错！当订单达到目标价的 50% 时，始终将止损拉至盈亏平衡 (BE)。',
      ko_rules: '이익을 얻는 것은 결코 잘못된 것이 아닙니다! 주문이 TP에 50% 도달하면 항상 손절매를 손익분기점(BE)으로 설정하세요.',
      es_rules: '¡Obtener ganancias nunca está mal! Utilice siempre Stop Loss para alcanzar el punto de equilibrio (BE) cuando la orden haya recorrido el 50% del camino hasta TP.',
      en_rules: 'Taking profits is never wrong! Always pull Stop Loss to Break Even (BE) when the order has gone 50% of the way to TP.',
      riskLevel: 'Trung Bình',
      zh_riskLevel: '中',
      ko_riskLevel: '보통',
      es_riskLevel: 'Medio',
      en_riskLevel: 'Medium',
      color: 'text-rose-400 border-rose-500/30 bg-rose-500/10'
    },
    {
      tag: '#Mistake_thuantrend_SLTooShort',
      label: 'Đánh Thuận Trend Nhưng Cài SL Quá Ngắn',
      zh_label: '战胜趋势但设置止损太短',
      ko_label: '추세를 앞서지만 SL을 너무 짧게 설정',
      es_label: 'Vencer la tendencia pero establecer SL demasiado corto',
      en_label: 'Beating the Trend But Set SL Too Short',
      category: 'mistakes',
      group: 'Lỗi Kỹ Thuật',
      zh_group: '技术错误',
      ko_group: '기술적 오류',
      es_group: 'Error técnico',
      en_group: 'Technical Error',
      description: 'Phân tích đúng xu hướng tăng/giảm nhưng cài SL quá sát râu nến M1, bị quét râu nến rồi giá mới chạy đúng hướng.',
      zh_description: '正确分析上涨/下跌趋势，但将止损设置得太接近 M1 烛台的影线，烛台的影线会在价格向正确的方向移动之前被扫除。',
      ko_description: '상승/하락 추세를 올바르게 분석했지만 SL을 M1 촛대 심지에 너무 가깝게 설정하면 가격이 올바른 방향으로 움직이기 전에 촛대 심지가 휩쓸립니다.',
      es_description: 'Al analizar correctamente la tendencia al alza/a la baja, pero al establecer el SL demasiado cerca de la mecha de la vela M1, la mecha de la vela se barre antes de que el precio se mueva en la dirección correcta.',
      en_description: 'Analyzing the up/down trend correctly but setting the SL too close to the M1 candlestick\'s wick, the candlestick\'s wick is swept before the price moves in the right direction.',
      rules: 'Đặt SL phải qua khỏi vùng cản + cộng thêm 3-5 pips buffer độ giãn spread của sàn.',
      zh_rules: '设置止损以通过阻力区域+为底价差添加 3-5 点缓冲。',
      ko_rules: '저항 영역을 통과하도록 SL을 설정하고 바닥 스프레드에 3-5핍 버퍼를 추가합니다.',
      es_rules: 'Configure el SL para pasar el área de resistencia + agregue 3-5 pips de amortiguación a la extensión del piso.',
      en_rules: 'Set the SL to pass the resistance area + add 3-5 pips buffer to the floor\'s spread.',
      riskLevel: 'Trung Bình',
      zh_riskLevel: '中',
      ko_riskLevel: '보통',
      es_riskLevel: 'Medio',
      en_riskLevel: 'Medium',
      color: 'text-rose-400 border-rose-500/30 bg-rose-500/10'
    },
    {
      tag: '#Mistake_CounterTrend_KyVongLon',
      label: 'Nghịch Trend Nhưng Kỳ Vọng TP Quá Lớn',
      zh_label: '逆势而上但TP预期太大',
      ko_label: '추세에 역행하지만 TP 기대치가 너무 큼',
      es_label: 'Yendo en contra de la tendencia, pero las expectativas de TP son demasiado grandes',
      en_label: 'Going Against the Trend But TP Expectations Are Too Big',
      category: 'mistakes',
      group: 'Lỗi Kỹ Thuật',
      zh_group: '技术错误',
      ko_group: '기술적 오류',
      es_group: 'Error técnico',
      en_group: 'Technical Error',
      description: 'Đánh sóng hồi ngược xu hướng lớn nhưng kỳ vọng ăn TP xa R:R 1:4 1:5, kết quả bị sóng chính đè bẹp.',
      zh_description: '打了一大波逆势，却期望TP离R:R 1:4 1:5很远，结果被主浪压垮了。',
      ko_description: '큰 역류 파도를 펼쳤지만 TP가 R:R 1:4 1:5에서 멀어질 것으로 예상하여 결과는 주요 파도에 의해 무너졌습니다.',
      es_description: 'Jugando una gran ola contratendencia pero esperando alejar a TP de R:R 1:4 1:5, el resultado fue aplastado por la ola principal.',
      en_description: 'Playing a big counter-trend wave but expecting to get TP far from R:R 1:4 1:5, the result was crushed by the main wave.',
      rules: 'Lệnh Counter-trend chỉ là lệnh lướt sóng ngắn. Đạt R:R 1:1 đến 1:1.5 là phải chủ động chốt sạch.',
      zh_rules: '逆势订单只是短期冲浪订单。实现 R:R 1:1 至 1:1.5 意味着您必须主动、干净地锁定。',
      ko_rules: '역추세 주문은 단기 서핑 주문일 뿐입니다. R:R 1:1 ~ 1:1.5를 달성한다는 것은 사전에 깨끗하게 고정해야 함을 의미합니다.',
      es_rules: 'Las órdenes contrarias a la tendencia son sólo órdenes de navegación a corto plazo. Lograr una R:R de 1:1 a 1:1,5 significa que debe fijarse de manera proactiva y limpia.',
      en_rules: 'Counter-trend orders are just short-term surfing orders. Achieving R:R 1:1 to 1:1.5 means you have to proactively lock in cleanly.',
      riskLevel: 'Cao',
      zh_riskLevel: '高',
      ko_riskLevel: '높음',
      es_riskLevel: 'Alto',
      en_riskLevel: 'High',
      color: 'text-rose-400 border-rose-500/30 bg-rose-500/10'
    },
    {
      tag: '#Mistake_CounterTrend',
      label: 'Bắt Đáy/Đỉnh Ngược Con Sóng Mạnh',
      zh_label: '抓住强浪的底部/顶部',
      ko_label: '강한 파도의 바닥/고점 잡기',
      es_label: 'Atrapando la parte inferior/superior de una ola fuerte',
      en_label: 'Catching the Bottom/Top of a Strong Wave',
      category: 'mistakes',
      group: 'Lỗi Kỹ Thuật',
      zh_group: '技术错误',
      ko_group: '기술적 오류',
      es_group: 'Error técnico',
      en_group: 'Technical Error',
      description: 'Thấy nến tăng/giảm quá mạnh liền nhảy vào chặn đầu xe tải (vào Sell khi cây nến xanh dựng đứng).',
      zh_description: '看到增减蜡烛太强，跳进去堵住卡车（当绿色蜡烛直立时进入卖出）。',
      ko_description: '증가/감소 양초가 너무 강한 것을 확인하고 뛰어들어 트럭을 막습니다(녹색 양초가 똑바로 서 있으면 Sell을 입력합니다).',
      es_description: 'Al ver que la vela de aumento/disminución es demasiado fuerte, salte y bloquee el camión (ingrese Vender cuando la vela verde esté en posición vertical).',
      en_description: 'Seeing that the increase/decrease candle is too strong, jump in and block the truck (enter Sell when the green candle stands upright).',
      rules: 'Chỉ đánh đảo chiều khi có gãy cấu trúc ChoCH / BOS. Tuyệt đối không đoán đỉnh/đáy cảm tính.',
      zh_rules: '仅当 ChoCH / BOS 结构出现断裂时才反转。绝对不要预测情绪的顶部/底部。',
      ko_rules: 'ChoCH/BOS 구조에 중단이 있는 경우에만 반전하십시오. 감정의 최고점/최저점을 절대 예측하지 마세요.',
      es_rules: 'Solo invierta cuando haya una ruptura en la estructura ChoCH/BOS. Absolutamente no prediga los altibajos emocionales.',
      en_rules: 'Only reverse when there is a break in the ChoCH / BOS structure. Absolutely do not predict emotional tops/bottoms.',
      riskLevel: 'Rất Cao',
      zh_riskLevel: '非常高',
      ko_riskLevel: '매우 높음',
      es_riskLevel: 'muy alto',
      en_riskLevel: 'Very High',
      color: 'text-rose-400 border-rose-500/30 bg-rose-500/10'
    },
    {
      tag: '#Mistake_EarlyEntry',
      label: 'Vào Lệnh Quá Sớm (Chưa Đóng Nến)',
      zh_label: '过早输入订单（蜡烛未关闭）',
      ko_label: '너무 일찍 주문을 입력함(캔들이 닫히지 않음)',
      es_label: 'Ingresar una orden demasiado pronto (vela no cerrada)',
      en_label: 'Entering an Order Too Early (Candle Not Closed)',
      category: 'mistakes',
      group: 'Lỗi Kỹ Thuật',
      zh_group: '技术错误',
      ko_group: '기술적 오류',
      es_group: 'Error técnico',
      en_group: 'Technical Error',
      description: 'Bấm lệnh khi cây nến xác nhận M5/M15 vẫn đang chạy chưa đóng cửa, sau đó nến quay xe rút chân ngược hoàn toàn.',
      zh_description: '当蜡烛确认M5/M15仍在运行且尚未关闭时按下订单，然后烛台将转向并完全收回其腿。',
      ko_description: '양초가 M5/M15가 여전히 작동 중이고 닫히지 않았음을 확인하면 주문을 누른 다음 촛대가 돌아서 다리를 완전히 빼냅니다.',
      es_description: 'Presione la orden cuando la vela confirme que M5/M15 sigue funcionando y no se ha cerrado, luego la vela gira y retira sus patas por completo.',
      en_description: 'Press the order when the candle confirms that M5/M15 is still running and has not closed, then the candlestick turns around and withdraws its legs completely.',
      rules: 'Luôn chờ đồng hồ đến ngược đóng cửa nến mới được quyết định bấm lệnh.',
      zh_rules: '在决定按下订单之前，请务必等待时钟关闭蜡烛。',
      ko_rules: '주문을 누르기로 결정하기 전에 항상 시계가 촛불을 닫을 때까지 기다리십시오.',
      es_rules: 'Espere siempre a que el reloj cierre la vela antes de decidir presionar la orden.',
      en_rules: 'Always wait for the clock to close the candle before deciding to press the order.',
      riskLevel: 'Trung Bình',
      zh_riskLevel: '中',
      ko_riskLevel: '보통',
      es_riskLevel: 'Medio',
      en_riskLevel: 'Medium',
      color: 'text-rose-400 border-rose-500/30 bg-rose-500/10'
    },
    {
      tag: '#Mistake_LateEntry',
      label: 'Vào Lệnh Trễ (Khoảng SL Quá Rộng)',
      zh_label: '迟到（SL 范围太宽）',
      ko_label: '늦은 진입(SL 범위가 너무 넓음)',
      es_label: 'Entrada tardía (rango SL demasiado amplio)',
      en_label: 'Late Entry (SL Range Too Wide)',
      category: 'mistakes',
      group: 'Lỗi Kỹ Thuật',
      zh_group: '技术错误',
      ko_group: '기술적 오류',
      es_group: 'Error técnico',
      en_group: 'Technical Error',
      description: 'Nến đóng xác nhận đẹp nhưng bận việc nhảy vào chậm 5-10 phút khiến khoảng cách SL bị phình to, tỷ lệ R:R cực tệ.',
      zh_description: '烛台收盘漂亮，但在晚了 5-10 分钟后忙于跳跃，导致止损缺口扩大，R:R 比率极其糟糕。',
      ko_description: '캔들은 아름답게 마감되었으나 5~10분 늦게 점핑하느라 SL 갭이 부풀어 오르고 R:R 비율이 극도로 나빴습니다.',
      es_description: 'La vela se cerró maravillosamente, pero estaba ocupada saltando entre 5 y 10 minutos tarde, lo que provocó que la brecha SL aumentara y la relación R:R fuera extremadamente mala.',
      en_description: 'The candlestick closed beautifully, but was busy jumping in 5-10 minutes late, causing the SL gap to swell and the R:R ratio to be extremely bad.',
      rules: 'Nếu Entry đã trôi quá 15 pips so với kế hoạch ban đầu -> Hủy kế hoạch, đợi cơ hội tiếp theo.',
      zh_rules: '如果入场点与原计划相比偏差超过 15 点 -> 取消计划，等待下一次机会。',
      ko_rules: '진입이 원래 계획에 비해 15핍 이상 변동된 경우 -> 계획 취소, 다음 기회를 기다리세요.',
      es_rules: 'Si la Entrada se ha desviado más de 15 pips en comparación con el plan original -> Cancelar el plan, esperar la próxima oportunidad.',
      en_rules: 'If the Entry has drifted more than 15 pips compared to the original plan -> Cancel the plan, wait for the next opportunity.',
      riskLevel: 'Trung Bình',
      zh_riskLevel: '中',
      ko_riskLevel: '보통',
      es_riskLevel: 'Medio',
      en_riskLevel: 'Medium',
      color: 'text-rose-400 border-rose-500/30 bg-rose-500/10'
    },
    {
      tag: '#Mistake_4thTouch',
      label: 'Vào Lệnh Ở Nhịp Chạm Cản Lần Thứ 4+',
      zh_label: '以第四次接触率输入订单+',
      ko_label: '4번째 터치율+로 주문 입력',
      es_label: 'Ingrese el pedido al cuarto toque +',
      en_label: 'Enter Order At 4th Touch Rate+',
      category: 'mistakes',
      group: 'Lỗi Kỹ Thuật',
      zh_group: '技术错误',
      ko_group: '기술적 오류',
      es_group: 'Error técnico',
      en_group: 'Technical Error',
      description: 'Vùng hỗ trợ/kháng cự đã bị đập đi đập lại 3-4 lần trở nên bị mòn yếu và chuẩn bị thủng bùng nổ.',
      zh_description: '支撑/阻力区被反复击打3-4次，变得疲软并即将爆发。',
      ko_description: '지지/저항 구간은 3~4회 반복해서 약해지며 폭발할 위기에 놓이게 됩니다.',
      es_description: 'La zona de soporte/resistencia ha sido golpeada una y otra vez 3 o 4 veces, debilitándose y a punto de explotar.',
      en_description: 'The support/resistance zone has been beaten over and over again 3-4 times, becoming weak and about to explode.',
      rules: 'Cản chỉ mạnh ở lần chạm thứ 1 và thứ 2. Từ lần thứ 4 tuyệt đối không đánh đảo chiều tại cản nữa.',
      zh_rules: '该阻挡仅在第一次和第二次触碰时较强。从第四次开始，绝对不要再在挡位上倒车了。',
      ko_rules: '블록은 1번째와 2번째 터치에만 강합니다. 4회부터는 절대 블록에서 후진하지 마세요.',
      es_rules: 'El bloqueo sólo es fuerte en el primer y segundo toque. A partir de la cuarta vez, no retroceda nunca más en el bloque.',
      en_rules: 'The block is only strong on the 1st and 2nd touches. From the 4th time, absolutely do not reverse at the block anymore.',
      riskLevel: 'Cao',
      zh_riskLevel: '高',
      ko_riskLevel: '높음',
      es_riskLevel: 'Alto',
      en_riskLevel: 'High',
      color: 'text-rose-400 border-rose-500/30 bg-rose-500/10'
    },
    {
      tag: '#Mistake_NewsTrading',
      label: 'Giao Dịch Sát Giờ Ra Tin Tức',
      zh_label: '临近新闻时间交易',
      ko_label: '뉴스 시간에 맞춰 거래',
      es_label: 'Negociación cerca de la hora de las noticias',
      en_label: 'Trading Close to News Time',
      category: 'mistakes',
      group: 'Lỗi Kỹ Thuật',
      zh_group: '技术错误',
      ko_group: '기술적 오류',
      es_group: 'Error técnico',
      en_group: 'Technical Error',
      description: 'Giữ lệnh hoặc bấm lệnh trước tin mạnh 5-10 phút (CPI, NFP, Fed FOMC). Độ giãn spread cực cao và quét 2 đầu.',
      zh_description: '持有订单或在强消息（CPI、NFP、美联储 FOMC）前 5-10 分钟按下订单。极高的扩散和双头扫描。',
      ko_description: '강한 소식(CPI, NFP, Fed FOMC)이 나오기 5~10분 전에 주문을 보류하거나 주문을 누르세요. 매우 높은 확산 및 이중 헤드 스캐닝.',
      es_description: 'Mantenga la orden o presione la orden entre 5 y 10 minutos antes de noticias importantes (IPC, NFP, Fed FOMC). Extensión extremadamente alta y escaneo de doble cabezal.',
      en_description: 'Hold the order or press the order 5-10 minutes before strong news (CPI, NFP, Fed FOMC). Extremely high spread and double-head scanning.',
      rules: 'Đóng bớt vị thế hoặc dời SL về BE trước giờ tin 15 phút. Không cờ bạc với tin tức.',
      zh_rules: '在新闻时间前 15 分钟平仓或将 SL 移至 BE。不要拿新闻来赌博。',
      ko_rules: '뉴스 시간 15분 전에 포지션을 청산하거나 SL을 BE로 이동하세요. 뉴스를 가지고 도박을 하지 마십시오.',
      es_rules: 'Cerrar posición o mover SL a BE 15 minutos antes de la hora de noticias. No juegues con las noticias.',
      en_rules: 'Close position or move SL to BE 15 minutes before news time. Don\'t gamble with the news.',
      riskLevel: 'Rất Cao',
      zh_riskLevel: '非常高',
      ko_riskLevel: '매우 높음',
      es_riskLevel: 'muy alto',
      en_riskLevel: 'Very High',
      color: 'text-rose-400 border-rose-500/30 bg-rose-500/10'
    },
  ],

  strengths: [
    {
      tag: '#Strength_StrictSL',
      label: 'Đặt Stop Loss Tuyệt Đối',
      zh_label: '设置绝对止损',
      ko_label: '절대 정지 손실 설정',
      es_label: 'Establecer Stop Loss absoluto',
      en_label: 'Set Absolute Stop Loss',
      category: 'strengths',
      group: 'Thói Quen Tốt & Kỷ Luật',
      zh_group: '良好的习惯和纪律',
      ko_group: '좋은 습관과 규율',
      es_group: 'Buenos hábitos y disciplina',
      en_group: 'Good Habits & Discipline',
      description: 'Luôn tính toán khoảng cách Stop Loss và cài đặt ngay tức thì khi nhấn lệnh vào thị trường.',
      zh_description: '在市场下单时，务必计算止损距离并立即设置。',
      ko_description: '항상 손절매 거리를 계산하고 시장에 주문할 때 즉시 설정하십시오.',
      es_description: 'Calcule siempre la distancia de Stop Loss y configúrela inmediatamente al realizar una orden en el mercado.',
      en_description: 'Always calculate the Stop Loss distance and set it immediately when placing an order on the market.',
      rules: 'Hành vi chuẩn mực giúp bảo vệ tài khoản sống sót dài lâu.',
      zh_rules: '标准行为有助于保护长期生存账户。',
      ko_rules: '표준 동작은 장기 생존 계정을 보호하는 데 도움이 됩니다.',
      es_rules: 'El comportamiento estándar ayuda a proteger las cuentas de supervivencia a largo plazo.',
      en_rules: 'Standard behavior helps protect long-term survival accounts.',
      riskLevel: 'Thói Quen Tốt',
      zh_riskLevel: '好习惯',
      ko_riskLevel: '좋은 습관',
      es_riskLevel: 'Buenos hábitos',
      en_riskLevel: 'Good Habits',
      color: 'text-sky-400 border-sky-500/30 bg-sky-500/10'
    },
    {
      tag: '#Strength_CounterTrend_Scalp',
      label: 'Ngược Trend Chỉ Scalp TP Ngắn',
      zh_label: '仅限反趋势头皮 TP 空头',
      ko_label: '카운터트렌드온리 스칼프 TP 숏',
      es_label: 'Contratendencia únicamente Scalp Short TP',
      en_label: 'Counter Trend Only Scalp Short TP',
      category: 'strengths',
      group: 'Thói Quen Tốt & Kỷ Luật',
      zh_group: '良好的习惯和纪律',
      ko_group: '좋은 습관과 규율',
      es_group: 'Buenos hábitos y disciplina',
      en_group: 'Good Habits & Discipline',
      description: 'Nhận diện rõ đây là lệnh Counter-Trend nên chủ động chốt lời ngắn 1:1, không tham gồng xa.',
      zh_description: '清楚认识到这是反趋势订单，所以主动以1：1的方式获利了结，不要走得太远。',
      ko_description: '이것이 역추세 주문임을 분명히 인식하고 적극적으로 1:1로 짧은 이익을 취하고 너무 멀리 가지 마십시오.',
      es_description: 'Reconozca claramente que se trata de una orden contratendencia, por lo que debe tomar ganancias cortas de manera proactiva 1:1, no vaya demasiado lejos.',
      en_description: 'Clearly recognize that this is a Counter-Trend order so proactively take short profits 1:1, do not go too far.',
      rules: 'Kỷ luật kiểm soát kỳ vọng chuẩn xác.',
      zh_rules: '纪律准确地控制期望。',
      ko_rules: '규율은 기대치를 정확하게 통제합니다.',
      es_rules: 'La disciplina controla las expectativas con precisión.',
      en_rules: 'Discipline controls expectations accurately.',
      riskLevel: 'Thói Quen Tốt',
      zh_riskLevel: '好习惯',
      ko_riskLevel: '좋은 습관',
      es_riskLevel: 'Buenos hábitos',
      en_riskLevel: 'Good Habits',
      color: 'text-sky-400 border-sky-500/30 bg-sky-500/10'
    },
    {
      tag: '#Strength_LockProfit',
      label: 'Kéo SL Về Hòa Vốn (Lock BE)',
      zh_label: '拉动 SL 至盈亏平衡（锁定 BE）',
      ko_label: 'SL을 손익분기점으로 끌어당김(BE 고정)',
      es_label: 'Tire de SL para alcanzar el punto de equilibrio (Bloquear BE)',
      en_label: 'Pull SL to Break Even (Lock BE)',
      category: 'strengths',
      group: 'Thói Quen Tốt & Kỷ Luật',
      zh_group: '良好的习惯和纪律',
      ko_group: '좋은 습관과 규율',
      es_group: 'Buenos hábitos y disciplina',
      en_group: 'Good Habits & Discipline',
      description: 'Kéo Stop Loss về điểm Entry (Break-even) khi giá chạy đủ +30 pips an toàn để đưa vị thế về rủi ro 0%.',
      zh_description: '当价格运行足够+30 安全点以使仓位风险降至 0% 时，将止损拉至入场点（盈亏平衡）。',
      ko_description: '가격이 +30 안전 핍만큼 충분히 상승하여 포지션의 위험이 0%가 되면 정지 손실을 진입점(손익분기점)으로 끌어옵니다.',
      es_description: 'Lleve el Stop Loss al punto de entrada (punto de equilibrio) cuando el precio alcance suficientes +30 pips seguros para llevar la posición al 0% de riesgo.',
      en_description: 'Pull Stop Loss to the Entry point (Break-even) when the price runs enough +30 safe pips to bring the position to 0% risk.',
      rules: 'Giúp loại bỏ 100% áp lực tâm lý cho tài khoản.',
      zh_rules: '帮助消除账户100%的心理压力。',
      ko_rules: '계정에 대한 심리적 압박을 100% 제거하는 데 도움이 됩니다.',
      es_rules: 'Ayuda a eliminar 100% la presión psicológica sobre la cuenta.',
      en_rules: 'Helps eliminate 100% psychological pressure on the account.',
      riskLevel: 'Thói Quen Tốt',
      zh_riskLevel: '好习惯',
      ko_riskLevel: '좋은 습관',
      es_riskLevel: 'Buenos hábitos',
      en_riskLevel: 'Good Habits',
      color: 'text-sky-400 border-sky-500/30 bg-sky-500/10'
    },
    {
      tag: '#Strength_AdjustTP',
      label: 'Chủ Động Chốt Lời Khi Thấy Cản Phụ',
      zh_label: '当看到障碍时主动获利了结',
      ko_label: '장애물이 보일 때 적극적으로 이익을 취하세요',
      es_label: 'Obtenga ganancias de manera proactiva cuando vea obstáculos',
      en_label: 'Proactively Take Profits When You See Obstacles',
      category: 'strengths',
      group: 'Thói Quen Tốt & Kỷ Luật',
      zh_group: '良好的习惯和纪律',
      ko_group: '좋은 습관과 규율',
      es_group: 'Buenos hábitos y disciplina',
      en_group: 'Good Habits & Discipline',
      description: 'Linh hoạt chốt lời sớm khi quan sát thấy cấu trúc nến M1/M5 tạo cản phụ cản đường sóng.',
      zh_description: '当观察 M1/M5 烛台结构形成阻挡波浪路径的额外障碍时，尽早灵活获利。',
      ko_description: 'M1/M5 촛대 구조를 관찰하여 파도 경로를 차단하는 추가 장벽을 생성하여 유연하게 조기에 수익을 얻으십시오.',
      es_description: 'Tome ganancias de manera flexible desde el principio al observar la estructura de velas M1/M5, creando una barrera adicional que bloquea la trayectoria de la onda.',
      en_description: 'Flexibly take profits early when observing the M1/M5 candlestick structure creating an additional barrier blocking the wave path.',
      rules: 'Hiện thực hóa lợi nhuận thay vì cứng nhắc gồng TP ban đầu.',
      zh_rules: '实现利润而不是死守最初的目标价。',
      ko_rules: '초기 TP를 굳게 붙잡는 대신 이익을 실현하세요.',
      es_rules: 'Obtenga ganancias en lugar de aferrarse rígidamente al TP inicial.',
      en_rules: 'Realize profits instead of rigidly holding on to the initial TP.',
      riskLevel: 'Thói Quen Tốt',
      zh_riskLevel: '好习惯',
      ko_riskLevel: '좋은 습관',
      es_riskLevel: 'Buenos hábitos',
      en_riskLevel: 'Good Habits',
      color: 'text-sky-400 border-sky-500/30 bg-sky-500/10'
    },
    {
      tag: '#Strength_RiskManaged',
      label: 'Quản Lý Rủi Ro Cố Định 1-2%',
      zh_label: '固定风险管理 1-2%',
      ko_label: '고정 위험 관리 1-2%',
      es_label: 'Gestión de riesgos fijos 1-2%',
      en_label: 'Fixed Risk Management 1-2%',
      category: 'strengths',
      group: 'Thói Quen Tốt & Kỷ Luật',
      zh_group: '良好的习惯和纪律',
      ko_group: '좋은 습관과 규율',
      es_group: 'Buenos hábitos y disciplina',
      en_group: 'Good Habits & Discipline',
      description: 'Tính toán Lot chuẩn xác theo phần trăm tài khoản cố định (1-2%/lệnh) dù tâm lý đang thắng hay thua.',
      zh_description: '无论您是心理上赢还是输，都根据固定的账户百分比（1-2%/订单）准确计算手数。',
      ko_description: '승패 여부에 관계없이 고정 계정 비율(1-2%/주문)에 따라 랏을 정확하게 계산합니다.',
      es_description: 'Calcule los lotes con precisión de acuerdo con un porcentaje de cuenta fijo (1-2%/orden), ya sea que esté ganando o perdiendo mentalmente.',
      en_description: 'Calculate Lots accurately according to a fixed account percentage (1-2%/order) whether you are mentally winning or losing.',
      rules: 'Nền tảng quan trọng nhất của một Trader chuyên nghiệp.',
      zh_rules: '专业交易者最重要的基础。',
      ko_rules: '전문 트레이더의 가장 중요한 기초입니다.',
      es_rules: 'La base más importante de un Trader profesional.',
      en_rules: 'The most important foundation of a professional Trader.',
      riskLevel: 'Thói Quen Tốt',
      zh_riskLevel: '好习惯',
      ko_riskLevel: '좋은 습관',
      es_riskLevel: 'Buenos hábitos',
      en_riskLevel: 'Good Habits',
      color: 'text-sky-400 border-sky-500/30 bg-sky-500/10'
    },
    {
      tag: '#Strength_PatientWait',
      label: 'Kiên Nhẫn Chờ Đúng Setup',
      zh_label: '耐心等待正确设置',
      ko_label: '올바른 설정을 참을성 있게 기다리십시오.',
      es_label: 'Espere pacientemente hasta que la configuración sea correcta',
      en_label: 'Patiently Wait For Correct Setup',
      category: 'strengths',
      group: 'Thói Quen Tốt & Kỷ Luật',
      zh_group: '良好的习惯和纪律',
      ko_group: '좋은 습관과 규율',
      es_group: 'Buenos hábitos y disciplina',
      en_group: 'Good Habits & Discipline',
      description: 'Kiên nhẫn ngồi chờ giá về đúng Vùng Cản + Nến M5 đóng cửa xác nhận mới nhấn nút vào lệnh.',
      zh_description: '耐心等待价格到达阻力区 + M5 烛台收盘确认，然后再按下订单按钮。',
      ko_description: '가격이 저항 영역에 도달할 때까지 참을성 있게 기다리세요. 주문 버튼을 누르기 전에 확인을 위해 M5 촛대가 닫힙니다.',
      es_description: 'Espere pacientemente a que el precio alcance la zona de resistencia + cierre de la vela M5 para confirmar antes de presionar el botón de orden.',
      en_description: 'Patiently wait for the price to reach the Resistance Zone + M5 candlestick closes to confirm before pressing the order button.',
      rules: 'Loại bỏ hoàn toàn lệnh ẩu, lệnh ngứa tay.',
      zh_rules: '彻底杜绝不小心下单、手痒的情况。',
      ko_rules: '부주의한 주문과 가려운 손을 완전히 제거하세요.',
      es_rules: 'Elimina por completo los pedidos descuidados y el picor de manos.',
      en_rules: 'Completely eliminate careless orders and itchy hands.',
      riskLevel: 'Thói Quen Tốt',
      zh_riskLevel: '好习惯',
      ko_riskLevel: '좋은 습관',
      es_riskLevel: 'Buenos hábitos',
      en_riskLevel: 'Good Habits',
      color: 'text-sky-400 border-sky-500/30 bg-sky-500/10'
    },
    {
      tag: '#Strength_StopAfterWin',
      label: 'Đạt Hạn Mức Thắng Là Dừng',
      zh_label: '达到获胜限制后停止',
      ko_label: '승리 한도 도달이 중지됨',
      es_label: 'Se detiene el límite de ganancias',
      en_label: 'Reaching Win Limit Is Stopped',
      category: 'strengths',
      group: 'Thói Quen Tốt & Kỷ Luật',
      zh_group: '良好的习惯和纪律',
      ko_group: '좋은 습관과 규율',
      es_group: 'Buenos hábitos y disciplina',
      en_group: 'Good Habits & Discipline',
      description: 'Biết đủ là hạnh phúc: Khi đã đạt chỉ tiêu lợi nhuận trong ngày, chủ động đóng máy nghỉ ngơi.',
      zh_description: '知足就是幸福：当你达到当天的盈利目标时，主动关机休息。',
      ko_description: '충분히 아는 것이 행복입니다. 하루 수익 목표에 도달하면 적극적으로 기계를 닫고 휴식을 취하세요.',
      es_description: 'Saber lo suficiente es felicidad: cuando haya alcanzado su objetivo de ganancias del día, cierre proactivamente la máquina y descanse.',
      en_description: 'Knowing enough is happiness: When you have reached your profit target for the day, proactively close the machine and rest.',
      rules: 'Bảo vệ thành quả lợi nhuận tránh bị thị trường đòi lại.',
      zh_rules: '保护您的利润，避免被市场收回。',
      ko_rules: '시장에서 회수되지 않도록 이익을 보호하십시오.',
      es_rules: 'Proteja sus ganancias para evitar ser reclamado por el mercado.',
      en_rules: 'Protect your profits to avoid being reclaimed by the market.',
      riskLevel: 'Thói Quen Tốt',
      zh_riskLevel: '好习惯',
      ko_riskLevel: '좋은 습관',
      es_riskLevel: 'Buenos hábitos',
      en_riskLevel: 'Good Habits',
      color: 'text-sky-400 border-sky-500/30 bg-sky-500/10'
    },
    {
      tag: '#Strength_StopAfterLoss',
      label: 'Dừng Giao Dịch Đúng Hạn Mức Lỗ',
      zh_label: '在正确的损失限额处停止交易',
      ko_label: '적절한 손실 한도에서 거래를 중단하세요',
      es_label: 'Deje de operar con el límite de pérdidas adecuado',
      en_label: 'Stop Trading at the Right Loss Limit',
      category: 'strengths',
      group: 'Thói Quen Tốt & Kỷ Luật',
      zh_group: '良好的习惯和纪律',
      ko_group: '좋은 습관과 규율',
      es_group: 'Buenos hábitos y disciplina',
      en_group: 'Good Habits & Discipline',
      description: 'Khi chạm hạn mức thua lỗ cho phép trong ngày (Max Daily Loss 2-3%), kiên quyết ngắt điện đàm.',
      zh_description: '当达到当日允许损失限额（每日最大损失2-3%）时，坚决挂断电话。',
      ko_description: '하루 허용 손실 한도(최대 일일 손실 2~3%)에 도달하면 과감히 전화를 끊으세요.',
      es_description: 'Al alcanzar el límite de pérdida permitida para el día (pérdida diaria máxima 2-3%), desconecte resueltamente la llamada telefónica.',
      en_description: 'When reaching the allowable loss limit for the day (Max Daily Loss 2-3%), resolutely disconnect the phone call.',
      rules: 'Kỷ luật sắt ngăn chặn chuỗi dây chuyền ném tiền vào cửa tử.',
      zh_rules: '钢铁般的纪律可以阻止将钱投入死亡之门的链条。',
      ko_rules: '철칙은 죽음의 문에 돈을 던지는 사슬을 멈추게 합니다.',
      es_rules: 'Una disciplina de hierro detiene la cadena de arrojar dinero a las puertas de la muerte.',
      en_rules: 'Iron discipline stops the chain of throwing money into death\'s door.',
      riskLevel: 'Thói Quen Tốt',
      zh_riskLevel: '好习惯',
      ko_riskLevel: '좋은 습관',
      es_riskLevel: 'Buenos hábitos',
      en_riskLevel: 'Good Habits',
      color: 'text-sky-400 border-sky-500/30 bg-sky-500/10'
    },
    {
      tag: '#Strength_NoDCA',
      label: 'Nói Không Với DCA Âm',
      zh_label: '对负面 DCA 说不',
      ko_label: '부정적인 DCA에 반대하십시오',
      es_label: 'Di no al DCA negativo',
      en_label: 'Say No to Negative DCA',
      category: 'strengths',
      group: 'Thói Quen Tốt & Kỷ Luật',
      zh_group: '良好的习惯和纪律',
      ko_group: '좋은 습관과 규율',
      es_group: 'Buenos hábitos y disciplina',
      en_group: 'Good Habits & Discipline',
      description: 'Kiềm chế hoàn toàn ham muốn nhồi lệnh khi giá đang chạy ngược chiều.',
      zh_description: '完全抑制价格向相反方向移动时堆单的欲望。',
      ko_description: '가격이 반대 방향으로 움직일 때 주문을 채우려는 욕구를 완전히 억제하십시오.',
      es_description: 'Limite por completo el deseo de completar pedidos cuando el precio se mueve en la dirección opuesta.',
      en_description: 'Completely restrain the desire to stuff orders when the price is moving in the opposite direction.',
      rules: 'Nguyên tắc vàng giữ gìn sinh mạng tài khoản.',
      zh_rules: '黄金法则让您的帐户保持活力。',
      ko_rules: '황금률은 귀하의 계정을 유지합니다.',
      es_rules: 'La regla de oro mantiene viva tu cuenta.',
      en_rules: 'The golden rule keeps your account alive.',
      riskLevel: 'Thói Quen Tốt',
      zh_riskLevel: '好习惯',
      ko_riskLevel: '좋은 습관',
      es_riskLevel: 'Buenos hábitos',
      en_riskLevel: 'Good Habits',
      color: 'text-sky-400 border-sky-500/30 bg-sky-500/10'
    },
  ],
};

/**
 * Helper to find definition for a given tag
 */
export function getHashtagInfo(tagString, customTags = []) {
  if (!tagString) return null;
  const cleanTag = tagString.trim().toLowerCase();

  // Check custom tags first
  if (customTags && customTags.length > 0) {
    const customFound = customTags.find(item => item.tag.toLowerCase() === cleanTag);
    if (customFound) return customFound;
  }

  for (const catKey in OFFICIAL_HASHTAGS) {
    const found = OFFICIAL_HASHTAGS[catKey].find(
      item => item.tag.toLowerCase() === cleanTag
    );
    if (found) return found;
  }

  // Fallback for partial tag matches (e.g. #DCA, #LHRetest)
  for (const catKey in OFFICIAL_HASHTAGS) {
    const found = OFFICIAL_HASHTAGS[catKey].find(
      item => item.tag.toLowerCase().includes(cleanTag.replace('#', ''))
    );
    if (found) return found;
  }

  return null;
}

/**
 * Filter all glossary items for dictionary search & modal view
 */
export function getAllGlossaryItems(categoryFilter = 'all', searchQuery = '', customTags = []) {
  const mergedCustom = (customTags || []).map(i => ({
    ...i,
    cat: i.category || 'setups',
    catLabel: i.category === 'mistakes' ? '🔴 Lỗi Tâm Lý / Kỹ Thuật' :
              i.category === 'strengths' ? '🔵 Thói Quen Tốt & Kỷ Luật' :
              i.category === 'trends' ? '📈 Trend Xu Hướng' :
              i.category === 'sessions' ? '🌍 Phiên Giao Dịch' : '🟢 Setup Phương Pháp',
  }));

  const list = [
    ...OFFICIAL_HASHTAGS.sessions.map(i => ({ ...i, cat: 'sessions', catLabel: '🌍 Phiên Giao Dịch', en_catLabel: '🌍 Trading Session', zh_catLabel: '🌍 交易时段', ko_catLabel: '🌍 거래 세션', es_catLabel: '🌍 Sesión de Trading' })),
    ...OFFICIAL_HASHTAGS.setups.map(i => ({ ...i, cat: 'setups', catLabel: '🟢 Setup Phương Pháp', en_catLabel: '🟢 Methodology Setup', zh_catLabel: '🟢 交易策略 Setup', ko_catLabel: '🟢 셋업 전략', es_catLabel: '🟢 Configuración del Método' })),
    ...OFFICIAL_HASHTAGS.trends.map(i => ({ ...i, cat: 'trends', catLabel: '📈 Trend Xu Hướng', en_catLabel: '📈 Trend Direction', zh_catLabel: '📈 趋势方向', ko_catLabel: '📈 추세 방향', es_catLabel: '📈 Dirección de Tendencia' })),
    ...OFFICIAL_HASHTAGS.mistakes.map(i => ({ ...i, cat: 'mistakes', catLabel: '🔴 Lỗi Tâm Lý / Kỹ Thuật', en_catLabel: '🔴 Psychology / Technical Error', zh_catLabel: '🔴 心理 / 技术错误', ko_catLabel: '🔴 심리 / 기술적 실수', es_catLabel: '🔴 Error Psicológico / Técnico' })),
    ...OFFICIAL_HASHTAGS.strengths.map(i => ({ ...i, cat: 'strengths', catLabel: '🔵 Thói Quen Tốt & Kỷ Luật', en_catLabel: '🔵 Good Habits & Discipline', zh_catLabel: '🔵 良好习惯与纪律', ko_catLabel: '🔵 좋은 습관 및 규율', es_catLabel: '🔵 Buenos Hábitos y Disciplina' })),
    ...mergedCustom,
  ];

  return list.filter(item => {
    const matchCat = categoryFilter === 'all' || item.cat === categoryFilter;
    const q = searchQuery.toLowerCase().trim();
    const matchSearch =
      !q ||
      item.tag.toLowerCase().includes(q) ||
      item.label?.toLowerCase().includes(q) ||
      item.description?.toLowerCase().includes(q) ||
      item.rules?.toLowerCase().includes(q) ||
      item.en_label?.toLowerCase().includes(q) ||
      item.en_description?.toLowerCase().includes(q) ||
      item.en_rules?.toLowerCase().includes(q) ||
      item.zh_label?.toLowerCase().includes(q) ||
      item.zh_description?.toLowerCase().includes(q) ||
      item.zh_rules?.toLowerCase().includes(q) ||
      item.ko_label?.toLowerCase().includes(q) ||
      item.ko_description?.toLowerCase().includes(q) ||
      item.ko_rules?.toLowerCase().includes(q) ||
      item.es_label?.toLowerCase().includes(q) ||
      item.es_description?.toLowerCase().includes(q) ||
      item.es_rules?.toLowerCase().includes(q);
    return matchCat && matchSearch;
  });
}

/**
 * Extract all hashtags from any text block
 */
export function parseHashtagsFromText(text = '') {
  if (!text) return [];
  const regex = /#[A-Za-z0-9_]+/g;
  const matches = text.match(regex);
  return matches ? Array.from(new Set(matches)) : [];
}
